;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |go| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#n| (svref (cdr |Γ|) 3)))
        (let ((|%to-string| (svref (cdr |Γ|) 2)))
          (let ((|%string-append| (svref (cdr |Γ|) 1)))
            (let ((|%println| (svref (cdr |Γ|) 0)))
              (let ((|_pL#acc| (car |α|)))
                (let ((|_pR#acc| (cdr |α|)))
                  (cond
                    ((equal |_pR#acc| 0)
                      (funcall |k| |_pL#acc|))
                    (t
                      (let ((|p3| (sb-kernel:two-arg-* |_pL#acc| |_pR#acc|)))
                        (let ((|c4| "fact "))
                          (let ((|p5| (sb-kernel:two-arg-- |_pL#n| |_pR#acc|)))
                            (let ((|u6| nil))
                              (let ((|pair7| (cons |p5| |u6|)))
                                (let ((|_code1017| (svref (cdr |%to-string|) 0)))
                                  (let ((|Γc1018| (svref (cdr |%to-string|) 1)))
                                    (let ((|ρc1019| (cons |pair7| |Γc1018|)))
                                      (labels ((|k1| (|v0|)
                                        (let ((|pair9| (cons |c4| |v0|)))
                                          (let ((|_code1014| (svref (cdr |%string-append|) 0)))
                                            (let ((|Γc1015| (svref (cdr |%string-append|) 1)))
                                              (let ((|ρc1016| (cons |pair9| |Γc1015|)))
                                                (labels ((|k3| (|v2|)
                                                  (let ((|c11| " = "))
                                                    (let ((|pair12| (cons |v2| |c11|)))
                                                      (let ((|_code1011| (svref (cdr |%string-append|) 0)))
                                                        (let ((|Γc1012| (svref (cdr |%string-append|) 1)))
                                                          (let ((|ρc1013| (cons |pair12| |Γc1012|)))
                                                            (labels ((|k5| (|v4|)
                                                              (let ((|u14| nil))
                                                                (let ((|pair15| (cons |p3| |u14|)))
                                                                  (let ((|_code1008| (svref (cdr |%to-string|) 0)))
                                                                    (let ((|Γc1009| (svref (cdr |%to-string|) 1)))
                                                                      (let ((|ρc1010| (cons |pair15| |Γc1009|)))
                                                                        (labels ((|k7| (|v6|)
                                                                          (let ((|pair17| (cons |v4| |v6|)))
                                                                            (let ((|_code1005| (svref (cdr |%string-append|) 0)))
                                                                              (let ((|Γc1006| (svref (cdr |%string-append|) 1)))
                                                                                (let ((|ρc1007| (cons |pair17| |Γc1006|)))
                                                                                  (labels ((|k9| (|v8|)
                                                                                    (let ((|u19| nil))
                                                                                      (let ((|pair20| (cons |v8| |u19|)))
                                                                                        (let ((|_code1002| (svref (cdr |%println|) 0)))
                                                                                          (let ((|Γc1003| (svref (cdr |%println|) 1)))
                                                                                            (let ((|ρc1004| (cons |pair20| |Γc1003|)))
                                                                                              (labels ((|k11| (|v10|)
                                                                                                (let ((|c22| 1))
                                                                                                  (let ((|p23| (sb-kernel:two-arg-- |_pR#acc| |c22|)))
                                                                                                    (let ((|pair24| (cons |p3| |p23|)))
                                                                                                      (let ((|ρ1001| (cons |pair24| |Γ|)))
                                                                                                        (funcall #'|go| |ρ1001| |k|)))))))
                                                                                                (funcall |_code1002| |ρc1004| #'|k11|)))))))))
                                                                                    (funcall |_code1005| |ρc1007| #'|k9|))))))))
                                                                          (funcall |_code1008| |ρc1010| #'|k7|)))))))))
                                                              (funcall |_code1011| |ρc1013| #'|k5|)))))))))
                                                  (funcall |_code1014| |ρc1016| #'|k3|))))))))
                                        (funcall |_code1017| |ρc1019| #'|k1|)))))))))))))))))))))

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|%to-string| (svref (cdr |Γ|) 2)))
        (let ((|%string-append| (svref (cdr |Γ|) 1)))
          (let ((|%println| (svref (cdr |Γ|) 0)))
            (let ((|_pL#n| (car |α|)))
              (let ((|Γ| (cons '|𝐄| (vector |%println| |%string-append| |%to-string| |_pL#n|))))
                (let ((|go#clo1023| (cons '|𝐂| (vector #'|go| |Γ|))))
                  (let ((|c26| 1))
                    (let ((|pair27| (cons |c26| |_pL#n|)))
                      (let ((|_code1020| (svref (cdr |go#clo1023|) 0)))
                        (let ((|Γc1021| (svref (cdr |go#clo1023|) 1)))
                          (let ((|ρc1022| (cons |pair27| |Γc1021|)))
                            (funcall |_code1020| |ρc1022| |k|)))))))))))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector |%println| |%string-append| |%to-string|))))
    (let ((|lam29| (cons '|𝐂| (vector #'|fn1000| |Γ|))))
      (let ((|c30| 5))
        (let ((|u31| nil))
          (let ((|pair32| (cons |c30| |u31|)))
            (let ((|_code1024| (svref (cdr |lam29|) 0)))
              (let ((|Γc1025| (svref (cdr |lam29|) 1)))
                (let ((|ρc1026| (cons |pair32| |Γc1025|)))
                  (funcall |_code1024| |ρc1026| |k|))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

