
; hoisted functions

(defun |eval| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#?x₀| (car |α|)))
        (cond
          ((eq (car |_pL#?x₀|) '|Add|)
            (let ((|p1| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|p2| (svref (cdr |_pL#?x₀|) 1)))
                (let ((|u3| nil))
                  (let ((|pair4| (cons |p1| |u3|)))
                    (let ((|ρ1001| (cons |pair4| |Γ|)))
                      (labels ((|k1| (|v0|)
                        (let ((|u6| nil))
                          (let ((|pair7| (cons |p2| |u6|)))
                            (let ((|ρ1000| (cons |pair7| |Γ|)))
                              (labels ((|k3| (|v2|)
                                (let ((|p9| (tigris-ffi:%int+ |v0| |v2|)))
                                  (funcall |k| |p9|))))
                                (funcall #'|eval| |ρ1000| #'|k3|)))))))
                        (funcall #'|eval| |ρ1001| #'|k1|))))))))
          ((eq (car |_pL#?x₀|) '|Div|)
            (let ((|p10| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|p11| (svref (cdr |_pL#?x₀|) 1)))
                (let ((|u12| nil))
                  (let ((|pair13| (cons |p10| |u12|)))
                    (let ((|ρ1003| (cons |pair13| |Γ|)))
                      (labels ((|k5| (|v4|)
                        (let ((|u15| nil))
                          (let ((|pair16| (cons |p11| |u15|)))
                            (let ((|ρ1002| (cons |pair16| |Γ|)))
                              (labels ((|k7| (|v6|)
                                (let ((|p18| (tigris-ffi:%int/ |v4| |v6|)))
                                  (funcall |k| |p18|))))
                                (funcall #'|eval| |ρ1002| #'|k7|)))))))
                        (funcall #'|eval| |ρ1003| #'|k5|))))))))
          ((eq (car |_pL#?x₀|) '|Mul|)
            (let ((|p19| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|p20| (svref (cdr |_pL#?x₀|) 1)))
                (let ((|u21| nil))
                  (let ((|pair22| (cons |p19| |u21|)))
                    (let ((|ρ1005| (cons |pair22| |Γ|)))
                      (labels ((|k9| (|v8|)
                        (let ((|u24| nil))
                          (let ((|pair25| (cons |p20| |u24|)))
                            (let ((|ρ1004| (cons |pair25| |Γ|)))
                              (labels ((|k11| (|v10|)
                                (let ((|p27| (tigris-ffi:%int* |v8| |v10|)))
                                  (funcall |k| |p27|))))
                                (funcall #'|eval| |ρ1004| #'|k11|)))))))
                        (funcall #'|eval| |ρ1005| #'|k9|))))))))
          ((eq (car |_pL#?x₀|) '|Atom|)
            (let ((|p28| (svref (cdr |_pL#?x₀|) 0)))
              (funcall |k| |p28|)))
          ((eq (car |_pL#?x₀|) '|Sub|)
            (let ((|p29| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|p30| (svref (cdr |_pL#?x₀|) 1)))
                (let ((|u31| nil))
                  (let ((|pair32| (cons |p29| |u31|)))
                    (let ((|ρ1007| (cons |pair32| |Γ|)))
                      (labels ((|k13| (|v12|)
                        (let ((|u34| nil))
                          (let ((|pair35| (cons |p30| |u34|)))
                            (let ((|ρ1006| (cons |pair35| |Γ|)))
                              (labels ((|k15| (|v14|)
                                (let ((|p37| (tigris-ffi:%int- |v12| |v14|)))
                                  (funcall |k| |p37|))))
                                (funcall #'|eval| |ρ1006| #'|k15|)))))))
                        (funcall #'|eval| |ρ1007| #'|k13|)))))))))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|c38| 20))
      (let ((|con39| (cons '|Atom| (vector |c38|))))
        (let ((|c40| 10))
          (let ((|con41| (cons '|Atom| (vector |c40|))))
            (let ((|c42| 20))
              (let ((|con43| (cons '|Atom| (vector |c42|))))
                (let ((|con44| (cons '|Mul| (vector |con41| |con43|))))
                  (let ((|c45| 2400))
                    (let ((|con46| (cons '|Atom| (vector |c45|))))
                      (let ((|c47| 120))
                        (let ((|con48| (cons '|Atom| (vector |c47|))))
                          (let ((|c49| 10))
                            (let ((|con50| (cons '|Atom| (vector |c49|))))
                              (let ((|c51| 20))
                                (let ((|con52| (cons '|Atom| (vector |c51|))))
                                  (let ((|con53| (cons '|Mul| (vector |con50| |con52|))))
                                    (let ((|c54| 0))
                                      (let ((|con55| (cons '|Atom| (vector |c54|))))
                                        (let ((|con56| (cons '|Add| (vector |con53| |con55|))))
                                          (let ((|con57| (cons '|Add| (vector |con48| |con56|))))
                                            (let ((|con58| (cons '|Div| (vector |con46| |con57|))))
                                              (let ((|con59| (cons '|Sub| (vector |con44| |con58|))))
                                                (let ((|con60| (cons '|Mul| (vector |con39| |con59|))))
                                                  (let ((|u61| nil))
                                                    (let ((|pair62| (cons |con60| |u61|)))
                                                      (let ((|ρc1010| (cons |pair62| |Γ|)))
                                                        (labels ((|k17| (|v16|)
                                                          (let ((|c64| 3860))
                                                            (let ((|cmp65| (tigris-ffi:%int= |v16| |c64|)))
                                                              (if |cmp65|
                                                                (funcall |k| |con60|)
                                                                (error +NOMATCH+ :discr "#[Toplevel]"))))))
                                                          (funcall #'|eval| |ρc1010| #'|k17|))))))))))))))))))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

