;; == Common Lisp ==

; hoisted functions

(defun |map| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#f| (car |α|)))
      (let ((|_pR#f| (cdr |α|)))
        (cond
          ((eq (car |_pR#f|) '|Nil|)
            (let ((|con2| (cons '|Nil| (vector))))
              (funcall |k| |con2|)))
          ((eq (car |_pR#f|) '|Cons|)
            (let ((|p3| (svref (cdr |_pR#f|) 0)))
              (let ((|p4| (svref (cdr |_pR#f|) 1)))
                (let ((|_code| (svref (cdr |_pL#f|) 0)))
                  (let ((|Γ| (svref (cdr |_pL#f|) 1)))
                    (let ((|ρ| (cons |p3| |Γ|)))
                      (labels ((|k1| (|v0|)
                        (let ((|pair6| (cons |_pL#f| |p4|)))
                          (let ((|ρ| (cons |pair6| |Γ|)))
                            (labels ((|k3| (|v2|)
                              (let ((|con8| (cons '|Cons| (vector |v0| |v2|))))
                                (funcall |k| |con8|))))
                              (funcall #'|map| |ρ| #'|k3|))))))
                        (funcall |_code| |ρ| #'|k1|)))))))))))))

(defun |foldl| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#f| (car |α|)))
      (let ((|_pR#f| (cdr |α|)))
        (let ((|_pL#init| (car |_pR#f|)))
          (let ((|_pR#init| (cdr |_pR#f|)))
            (cond
              ((eq (car |_pR#init|) '|Nil|)
                (funcall |k| |_pL#init|))
              ((eq (car |_pR#init|) '|Cons|)
                (let ((|p11| (svref (cdr |_pR#init|) 0)))
                  (let ((|p12| (svref (cdr |_pR#init|) 1)))
                    (let ((|pair13| (cons |_pL#init| |p11|)))
                      (let ((|_code| (svref (cdr |_pL#f|) 0)))
                        (let ((|Γ| (svref (cdr |_pL#f|) 1)))
                          (let ((|ρ| (cons |pair13| |Γ|)))
                            (labels ((|k5| (|v4|)
                              (let ((|pair16| (cons |v4| |p12|)))
                                (let ((|pair15| (cons |_pL#f| |pair16|)))
                                  (let ((|ρ| (cons |pair15| |Γ|)))
                                    (funcall #'|foldl| |ρ| |k|))))))
                              (funcall |_code| |ρ| #'|k5|))))))))))))))))

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (cond
      ((eq (car |α|) '|Cons|)
        (let ((|p19| (svref (cdr |α|) 0)))
          (funcall |k| |p19|)))
      (t
        (let ((|u18| nil))
          (funcall |k| |u18|))))))

(defun |fn1001| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|c33| 1))
      (let ((|p34| (+ |c33| |α|)))
        (funcall |k| |p34|)))))

(defun |fn1005| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#__?x₀| (car |α|)))
      (let ((|_pR#__?x₀| (cdr |α|)))
        (let ((|p39| (+ |_pL#__?x₀| |_pR#__?x₀|)))
          (funcall |k| |p39|))))))

(defun |fn1009| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#__?x₀| (car |α|)))
      (let ((|_pR#__?x₀| (cdr |α|)))
        (let ((|p46| (+ |_pL#__?x₀| |_pR#__?x₀|)))
          (funcall |k| |p46|))))))

; entrypoint
(defun |main| (|arg| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|map| (cons '|𝐂| (vector #'|map| |Γ|))))
      (let ((|Γ| (cons '|𝐄| (vector))))
        (let ((|foldl| (cons '|𝐂| (vector #'|foldl| |Γ|))))
          (let ((|c24| 1))
            (let ((|c25| 2))
              (let ((|c26| 3))
                (let ((|c27| 4))
                  (let ((|con28| (cons '|Nil| (vector))))
                    (let ((|con29| (cons '|Cons| (vector |c27| |con28|))))
                      (let ((|con30| (cons '|Cons| (vector |c26| |con29|))))
                        (let ((|con31| (cons '|Cons| (vector |c25| |con30|))))
                          (let ((|con32| (cons '|Cons| (vector |c24| |con31|))))
                            (let ((|Γ| (cons '|𝐄| (vector))))
                              (let ((|lam35| (cons '|𝐂| (vector #'|fn1001| |Γ|))))
                                (let ((|pair36| (cons |lam35| |con32|)))
                                  (let ((|ρ1004| (cons |pair36| |Γ|)))
                                    (labels ((|k7| (|v6|)
                                      (let ((|Γ| (cons '|𝐄| (vector))))
                                        (let ((|lam40| (cons '|𝐂| (vector #'|fn1005| |Γ|))))
                                          (let ((|c41| 0))
                                            (let ((|pair43| (cons |c41| |con32|)))
                                              (let ((|pair42| (cons |lam40| |pair43|)))
                                                (let ((|ρ1008| (cons |pair42| |Γ|)))
                                                  (labels ((|k9| (|v8|)
                                                    (let ((|Γ| (cons '|𝐄| (vector))))
                                                      (let ((|lam47| (cons '|𝐂| (vector #'|fn1009| |Γ|))))
                                                        (let ((|c48| 0))
                                                          (let ((|pair50| (cons |c48| |v6|)))
                                                            (let ((|pair49| (cons |lam47| |pair50|)))
                                                              (let ((|ρ1012| (cons |pair49| |Γ|)))
                                                                (labels ((|k11| (|v10|)
                                                                  (let ((|ρ1015| (cons |v6| |Γ|)))
                                                                    (labels ((|k13| (|v12|)
                                                                      (let ((|p53| (cons |v10| |v12|)))
                                                                        (let ((|p54| (cons |v8| |p53|)))
                                                                          (let ((|p55| (cons |v6| |p54|)))
                                                                            (funcall |k| |p55|))))))
                                                                      (funcall #'|fn1000| |ρ1015| #'|k13|)))))
                                                                  (funcall #'|foldl| |ρ1012| #'|k11|))))))))))
                                                    (funcall #'|foldl| |ρ1008| #'|k9|))))))))))
                                      (funcall #'|map| |ρ1004| #'|k7|))))))))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

