;; == Runtime ==
(load "runtime.lisp")

;; == Linked Lisp Source ==
(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1006| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1007| (car |payload|)))
    (let ((|Γ1008| (cdr |payload|)))
      (let ((|_pL#x| (svref (cdr |Γ1008|) 0)))
        (let ((|_pL#k| (car |α1007|)))
          (let ((|u2| nil))
            (let ((|pair3| (cons |_pL#x| |u2|)))
              (let ((|_code1009| (svref (cdr |_pL#k|) 0)))
                (let ((|Γc1010| (svref (cdr |_pL#k|) 1)))
                  (let ((|ρc1011| (cons |pair3| |Γc1010|)))
                    (funcall (the function |_code1009|) |ρc1011| |k|)))))))))))

(defun |fn1003| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1004| (car |payload|)))
    (let ((|_pL#x| (car |α1004|)))
      (let ((|Γ1012| (cons '|𝐄| (vector |_pL#x|))))
        (let ((|lam5| (cons '|𝐂| (vector #'|fn1006| |Γ1012|))))
          (let ((|con6| (cons '|Cont| (vector |lam5|))))
            (funcall (the function |k|) |con6|)))))))

(defun |fn1013| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1014| (car |payload|)))
    (let ((|_pL#c| (car |α1014|)))
      (let ((|_pR#c| (cdr |α1014|)))
        (cond
          ((eq (car |_pL#c|) '|Cont|)
            (let ((|p9| (svref (cdr |_pL#c|) 0)))
              (let ((|u10| nil))
                (let ((|pair11| (cons |_pR#c| |u10|)))
                  (let ((|_code1016| (svref (cdr |p9|) 0)))
                    (let ((|Γc1017| (svref (cdr |p9|) 1)))
                      (let ((|ρc1018| (cons |pair11| |Γc1017|)))
                        (funcall (the function |_code1016|) |ρc1018| |k|)))))))))))))

(defun |fn1025| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1026| (car |payload|)))
    (let ((|Γ1027| (cdr |payload|)))
      (let ((|_pR#?x₀| (svref (cdr |Γ1027|) 1)))
        (let ((|_pL#k| (svref (cdr |Γ1027|) 0)))
          (let ((|_pL#a| (car |α1026|)))
            (let ((|u18| nil))
              (let ((|pair19| (cons |_pL#a| |u18|)))
                (let ((|_code1031| (svref (cdr |_pR#?x₀|) 0)))
                  (let ((|Γc1032| (svref (cdr |_pR#?x₀|) 1)))
                    (let ((|ρc1033| (cons |pair19| |Γc1032|)))
                      (labels ((|k1| (|v0|)
                        (cond
                          ((eq (car |v0|) '|Cont|)
                            (let ((|p21| (svref (cdr |v0|) 0)))
                              (let ((|u22| nil))
                                (let ((|pair23| (cons |_pL#k| |u22|)))
                                  (let ((|_code1028| (svref (cdr |p21|) 0)))
                                    (let ((|Γc1029| (svref (cdr |p21|) 1)))
                                      (let ((|ρc1030| (cons |pair23| |Γc1029|)))
                                        (funcall (the function |_code1028|) |ρc1030| |k|)))))))))))
                        (funcall (the function |_code1031|) |ρc1033| #'|k1|)))))))))))))

(defun |fn1022| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1023| (car |payload|)))
    (let ((|Γ1024| (cdr |payload|)))
      (let ((|p15| (svref (cdr |Γ1024|) 1)))
        (let ((|_pR#?x₀| (svref (cdr |Γ1024|) 0)))
          (let ((|_pL#k| (car |α1023|)))
            (let ((|Γ1037| (cons '|𝐄| (vector |_pL#k| |_pR#?x₀|))))
              (let ((|lam25| (cons '|𝐂| (vector #'|fn1025| |Γ1037|))))
                (let ((|u26| nil))
                  (let ((|pair27| (cons |lam25| |u26|)))
                    (let ((|_code1034| (svref (cdr |p15|) 0)))
                      (let ((|Γc1035| (svref (cdr |p15|) 1)))
                        (let ((|ρc1036| (cons |pair27| |Γc1035|)))
                          (funcall (the function |_code1034|) |ρc1036| |k|))))))))))))))

(defun |fn1019| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1020| (car |payload|)))
    (let ((|_pL#?x₀| (car |α1020|)))
      (let ((|_pR#?x₀| (cdr |α1020|)))
        (cond
          ((eq (car |_pL#?x₀|) '|Cont|)
            (let ((|p15| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|Γ1038| (cons '|𝐄| (vector |_pR#?x₀| |p15|))))
                (let ((|lam29| (cons '|𝐂| (vector #'|fn1022| |Γ1038|))))
                  (let ((|con30| (cons '|Cont| (vector |lam29|))))
                    (funcall (the function |k|) |con30|)))))))))))

(defun |fn1048| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ1050| (cdr |payload|)))
    (let ((|_pL#k| (svref (cdr |Γ1050|) 1)))
      (let ((|_pL#a| (svref (cdr |Γ1050|) 0)))
        (let ((|u36| nil))
          (let ((|pair37| (cons |_pL#a| |u36|)))
            (let ((|_code1051| (svref (cdr |_pL#k|) 0)))
              (let ((|Γc1052| (svref (cdr |_pL#k|) 1)))
                (let ((|ρc1053| (cons |pair37| |Γc1052|)))
                  (funcall (the function |_code1051|) |ρc1053| |k|))))))))))

(defun |fn1045| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1046| (car |payload|)))
    (let ((|Γ1047| (cdr |payload|)))
      (let ((|_pL#k| (svref (cdr |Γ1047|) 0)))
        (let ((|_pL#a| (car |α1046|)))
          (let ((|Γ1054| (cons '|𝐄| (vector |_pL#a| |_pL#k|))))
            (let ((|lam39| (cons '|𝐂| (vector #'|fn1048| |Γ1054|))))
              (let ((|con40| (cons '|Cont| (vector |lam39|))))
                (funcall (the function |k|) |con40|)))))))))

(defun |fn1042| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1043| (car |payload|)))
    (let ((|Γ1044| (cdr |payload|)))
      (let ((|_pL#f| (svref (cdr |Γ1044|) 0)))
        (let ((|_pL#k| (car |α1043|)))
          (let ((|Γ1061| (cons '|𝐄| (vector |_pL#k|))))
            (let ((|lam41| (cons '|𝐂| (vector #'|fn1045| |Γ1061|))))
              (let ((|u42| nil))
                (let ((|pair43| (cons |lam41| |u42|)))
                  (let ((|_code1058| (svref (cdr |_pL#f|) 0)))
                    (let ((|Γc1059| (svref (cdr |_pL#f|) 1)))
                      (let ((|ρc1060| (cons |pair43| |Γc1059|)))
                        (labels ((|k3| (|v2|)
                          (cond
                            ((eq (car |v2|) '|Cont|)
                              (let ((|p45| (svref (cdr |v2|) 0)))
                                (let ((|u46| nil))
                                  (let ((|pair47| (cons |_pL#k| |u46|)))
                                    (let ((|_code1055| (svref (cdr |p45|) 0)))
                                      (let ((|Γc1056| (svref (cdr |p45|) 1)))
                                        (let ((|ρc1057| (cons |pair47| |Γc1056|)))
                                          (funcall (the function |_code1055|) |ρc1057| |k|)))))))))))
                          (funcall (the function |_code1058|) |ρc1060| #'|k3|))))))))))))))

(defun |fn1039| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1040| (car |payload|)))
    (let ((|_pL#f| (car |α1040|)))
      (let ((|Γ1062| (cons '|𝐄| (vector |_pL#f|))))
        (let ((|lam49| (cons '|𝐂| (vector #'|fn1042| |Γ1062|))))
          (let ((|con50| (cons '|Cont| (vector |lam49|))))
            (funcall (the function |k|) |con50|)))))))

(defun |fn1066| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ1068| (cdr |payload|)))
    (let ((|_pL#k| (svref (cdr |Γ1068|) 0)))
      (let ((|c58| 42))
        (let ((|u59| nil))
          (let ((|pair60| (cons |c58| |u59|)))
            (let ((|_code1069| (svref (cdr |_pL#k|) 0)))
              (let ((|Γc1070| (svref (cdr |_pL#k|) 1)))
                (let ((|ρc1071| (cons |pair60| |Γc1070|)))
                  (funcall (the function |_code1069|) |ρc1071| |k|))))))))))

(defun |fn1063| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1064| (car |payload|)))
    (let ((|Γ1065| (cdr |payload|)))
      (let ((|lam7| (svref (cdr |Γ1065|) 1)))
        (let ((|lam31| (svref (cdr |Γ1065|) 0)))
          (let ((|_pL#k| (car |α1064|)))
            (let ((|c53| 0))
              (let ((|u54| nil))
                (let ((|pair55| (cons |c53| |u54|)))
                  (let ((|_code1076| (svref (cdr |lam7|) 0)))
                    (let ((|Γc1077| (svref (cdr |lam7|) 1)))
                      (let ((|ρc1078| (cons |pair55| |Γc1077|)))
                        (labels ((|k5| (|v4|)
                          (let ((|Γ1075| (cons '|𝐄| (vector |_pL#k|))))
                            (let ((|lam62| (cons '|𝐂| (vector #'|fn1066| |Γ1075|))))
                              (let ((|pair63| (cons |v4| |lam62|)))
                                (let ((|_code1072| (svref (cdr |lam31|) 0)))
                                  (let ((|Γc1073| (svref (cdr |lam31|) 1)))
                                    (let ((|ρc1074| (cons |pair63| |Γc1073|)))
                                      (funcall (the function |_code1072|) |ρc1074| |k|)))))))))
                          (funcall (the function |_code1076|) |ρc1078| #'|k5|))))))))))))))

(defun |fn1079| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1080| (car |payload|)))
    (let ((|_pL#x| (car |α1080|)))
      (funcall (the function |k|) |_pL#x|))))

; entrypoint
(defun |main| (|payload1000| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1000|))
  (let ((|Γ1093| (cons '|𝐄| (vector))))
    (let ((|lam7| (cons '|𝐂| (vector #'|fn1003| |Γ1093|))))
      (let ((|Γ1092| (cons '|𝐄| (vector))))
        (let ((|lam13| (cons '|𝐂| (vector #'|fn1013| |Γ1092|))))
          (let ((|Γ1091| (cons '|𝐄| (vector))))
            (let ((|lam31| (cons '|𝐂| (vector #'|fn1019| |Γ1091|))))
              (let ((|Γ1090| (cons '|𝐄| (vector))))
                (let ((|Γ1089| (cons '|𝐄| (vector |lam31| |lam7|))))
                  (let ((|lam65| (cons '|𝐂| (vector #'|fn1063| |Γ1089|))))
                    (let ((|u66| nil))
                      (let ((|pair67| (cons |lam65| |u66|)))
                        (let ((|ρc1088| (cons |pair67| |Γ1090|)))
                          (labels ((|k7| (|v6|)
                            (let ((|Γ1085| (cons '|𝐄| (vector))))
                              (let ((|lam70| (cons '|𝐂| (vector #'|fn1079| |Γ1085|))))
                                (let ((|pair71| (cons |v6| |lam70|)))
                                  (let ((|_code1082| (svref (cdr |lam13|) 0)))
                                    (let ((|Γc1083| (svref (cdr |lam13|) 1)))
                                      (let ((|ρc1084| (cons |pair71| |Γc1083|)))
                                        (funcall (the function |_code1082|) |ρc1084| |k|)))))))))
                            (funcall #'|fn1039| |ρc1088| #'|k7|)))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

