;; == Runtime ==
(load "runtime.lisp")

;; == Linked Lisp Source ==
(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1001| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#x| (svref (cdr |Γ|) 0)))
        (let ((|_pL#k| (car |α|)))
          (let ((|u2| nil))
            (let ((|pair3| (cons |_pL#x| |u2|)))
              (let ((|_code1002| (svref (cdr |_pL#k|) 0)))
                (let ((|Γc1003| (svref (cdr |_pL#k|) 1)))
                  (let ((|ρc1004| (cons |pair3| |Γc1003|)))
                    (funcall (the function |_code1002|) |ρc1004| |k|)))))))))))

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (let ((|Γ| (cons '|𝐄| (vector |_pL#x|))))
        (let ((|lam5| (cons '|𝐂| (vector #'|fn1001| |Γ|))))
          (let ((|con6| (cons '|Cont| (vector |lam5|))))
            (funcall (the function |k|) |con6|)))))))

(defun |fn1005| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#c| (car |α|)))
      (let ((|_pR#c| (cdr |α|)))
        (cond
          ((eq (car |_pL#c|) '|Cont|)
            (let ((|p9| (svref (cdr |_pL#c|) 0)))
              (let ((|u10| nil))
                (let ((|pair11| (cons |_pR#c| |u10|)))
                  (let ((|_code1006| (svref (cdr |p9|) 0)))
                    (let ((|Γc1007| (svref (cdr |p9|) 1)))
                      (let ((|ρc1008| (cons |pair11| |Γc1007|)))
                        (funcall (the function |_code1006|) |ρc1008| |k|)))))))))))))

(defun |fn1011| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pR#?x₀| (svref (cdr |Γ|) 1)))
        (let ((|_pL#k| (svref (cdr |Γ|) 0)))
          (let ((|_pL#a| (car |α|)))
            (let ((|u18| nil))
              (let ((|pair19| (cons |_pL#a| |u18|)))
                (let ((|_code1015| (svref (cdr |_pR#?x₀|) 0)))
                  (let ((|Γc1016| (svref (cdr |_pR#?x₀|) 1)))
                    (let ((|ρc1017| (cons |pair19| |Γc1016|)))
                      (labels ((|k1| (|v0|)
                        (cond
                          ((eq (car |v0|) '|Cont|)
                            (let ((|p21| (svref (cdr |v0|) 0)))
                              (let ((|u22| nil))
                                (let ((|pair23| (cons |_pL#k| |u22|)))
                                  (let ((|_code1012| (svref (cdr |p21|) 0)))
                                    (let ((|Γc1013| (svref (cdr |p21|) 1)))
                                      (let ((|ρc1014| (cons |pair23| |Γc1013|)))
                                        (funcall (the function |_code1012|) |ρc1014| |k|)))))))))))
                        (funcall (the function |_code1015|) |ρc1017| #'|k1|)))))))))))))

(defun |fn1010| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|p15| (svref (cdr |Γ|) 1)))
        (let ((|_pR#?x₀| (svref (cdr |Γ|) 0)))
          (let ((|_pL#k| (car |α|)))
            (let ((|Γ| (cons '|𝐄| (vector |_pL#k| |_pR#?x₀|))))
              (let ((|lam25| (cons '|𝐂| (vector #'|fn1011| |Γ|))))
                (let ((|u26| nil))
                  (let ((|pair27| (cons |lam25| |u26|)))
                    (let ((|_code1018| (svref (cdr |p15|) 0)))
                      (let ((|Γc1019| (svref (cdr |p15|) 1)))
                        (let ((|ρc1020| (cons |pair27| |Γc1019|)))
                          (funcall (the function |_code1018|) |ρc1020| |k|))))))))))))))

(defun |fn1009| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|_pR#?x₀| (cdr |α|)))
        (cond
          ((eq (car |_pL#?x₀|) '|Cont|)
            (let ((|p15| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|Γ| (cons '|𝐄| (vector |_pR#?x₀| |p15|))))
                (let ((|lam29| (cons '|𝐂| (vector #'|fn1010| |Γ|))))
                  (let ((|con30| (cons '|Cont| (vector |lam29|))))
                    (funcall (the function |k|) |con30|)))))))))))

(defun |fn1024| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ| (cdr |payload|)))
    (let ((|_pL#k| (svref (cdr |Γ|) 1)))
      (let ((|_pL#a| (svref (cdr |Γ|) 0)))
        (let ((|u36| nil))
          (let ((|pair37| (cons |_pL#a| |u36|)))
            (let ((|_code1025| (svref (cdr |_pL#k|) 0)))
              (let ((|Γc1026| (svref (cdr |_pL#k|) 1)))
                (let ((|ρc1027| (cons |pair37| |Γc1026|)))
                  (funcall (the function |_code1025|) |ρc1027| |k|))))))))))

(defun |fn1023| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#k| (svref (cdr |Γ|) 0)))
        (let ((|_pL#a| (car |α|)))
          (let ((|Γ| (cons '|𝐄| (vector |_pL#a| |_pL#k|))))
            (let ((|lam39| (cons '|𝐂| (vector #'|fn1024| |Γ|))))
              (let ((|con40| (cons '|Cont| (vector |lam39|))))
                (funcall (the function |k|) |con40|)))))))))

(defun |fn1022| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#f| (svref (cdr |Γ|) 0)))
        (let ((|_pL#k| (car |α|)))
          (let ((|Γ| (cons '|𝐄| (vector |_pL#k|))))
            (let ((|lam41| (cons '|𝐂| (vector #'|fn1023| |Γ|))))
              (let ((|u42| nil))
                (let ((|pair43| (cons |lam41| |u42|)))
                  (let ((|_code1031| (svref (cdr |_pL#f|) 0)))
                    (let ((|Γc1032| (svref (cdr |_pL#f|) 1)))
                      (let ((|ρc1033| (cons |pair43| |Γc1032|)))
                        (labels ((|k3| (|v2|)
                          (cond
                            ((eq (car |v2|) '|Cont|)
                              (let ((|p45| (svref (cdr |v2|) 0)))
                                (let ((|u46| nil))
                                  (let ((|pair47| (cons |_pL#k| |u46|)))
                                    (let ((|_code1028| (svref (cdr |p45|) 0)))
                                      (let ((|Γc1029| (svref (cdr |p45|) 1)))
                                        (let ((|ρc1030| (cons |pair47| |Γc1029|)))
                                          (funcall (the function |_code1028|) |ρc1030| |k|)))))))))))
                          (funcall (the function |_code1031|) |ρc1033| #'|k3|))))))))))))))

(defun |fn1021| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#f| (car |α|)))
      (let ((|Γ| (cons '|𝐄| (vector |_pL#f|))))
        (let ((|lam49| (cons '|𝐂| (vector #'|fn1022| |Γ|))))
          (let ((|con50| (cons '|Cont| (vector |lam49|))))
            (funcall (the function |k|) |con50|)))))))

(defun |fn1035| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ| (cdr |payload|)))
    (let ((|_pL#k| (svref (cdr |Γ|) 0)))
      (let ((|c58| 42))
        (let ((|u59| nil))
          (let ((|pair60| (cons |c58| |u59|)))
            (let ((|_code1036| (svref (cdr |_pL#k|) 0)))
              (let ((|Γc1037| (svref (cdr |_pL#k|) 1)))
                (let ((|ρc1038| (cons |pair60| |Γc1037|)))
                  (funcall (the function |_code1036|) |ρc1038| |k|))))))))))

(defun |fn1034| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam7| (svref (cdr |Γ|) 1)))
        (let ((|lam31| (svref (cdr |Γ|) 0)))
          (let ((|_pL#k| (car |α|)))
            (let ((|c53| 0))
              (let ((|u54| nil))
                (let ((|pair55| (cons |c53| |u54|)))
                  (let ((|_code1042| (svref (cdr |lam7|) 0)))
                    (let ((|Γc1043| (svref (cdr |lam7|) 1)))
                      (let ((|ρc1044| (cons |pair55| |Γc1043|)))
                        (labels ((|k5| (|v4|)
                          (let ((|Γ| (cons '|𝐄| (vector |_pL#k|))))
                            (let ((|lam62| (cons '|𝐂| (vector #'|fn1035| |Γ|))))
                              (let ((|pair63| (cons |v4| |lam62|)))
                                (let ((|_code1039| (svref (cdr |lam31|) 0)))
                                  (let ((|Γc1040| (svref (cdr |lam31|) 1)))
                                    (let ((|ρc1041| (cons |pair63| |Γc1040|)))
                                      (funcall (the function |_code1039|) |ρc1041| |k|)))))))))
                          (funcall (the function |_code1042|) |ρc1044| #'|k5|))))))))))))))

(defun |fn1045| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (funcall (the function |k|) |_pL#x|))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|lam7| (cons '|𝐂| (vector #'|fn1000| |Γ|))))
      (let ((|Γ| (cons '|𝐄| (vector))))
        (let ((|lam13| (cons '|𝐂| (vector #'|fn1005| |Γ|))))
          (let ((|Γ| (cons '|𝐄| (vector))))
            (let ((|lam31| (cons '|𝐂| (vector #'|fn1009| |Γ|))))
              (let ((|Γ| (cons '|𝐄| (vector |lam31| |lam7|))))
                (let ((|lam65| (cons '|𝐂| (vector #'|fn1034| |Γ|))))
                  (let ((|u66| nil))
                    (let ((|pair67| (cons |lam65| |u66|)))
                      (let ((|ρc1051| (cons |pair67| |Γ|)))
                        (labels ((|k7| (|v6|)
                          (let ((|Γ| (cons '|𝐄| (vector))))
                            (let ((|lam70| (cons '|𝐂| (vector #'|fn1045| |Γ|))))
                              (let ((|pair71| (cons |v6| |lam70|)))
                                (let ((|_code1046| (svref (cdr |lam13|) 0)))
                                  (let ((|Γc1047| (svref (cdr |lam13|) 1)))
                                    (let ((|ρc1048| (cons |pair71| |Γc1047|)))
                                      (funcall (the function |_code1046|) |ρc1048| |k|)))))))))
                          (funcall #'|fn1021| |ρc1051| #'|k7|))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

