;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1001| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#x| (svref (cdr |Γ|) 0)))
        (let ((|_pL#k| (car |α|)))
          (let ((|u2| nil))
            (let ((|pair3| (cons |_pL#x| |u2|)))
              (let ((|_code1002| (svref (cdr |_pL#k|) 0)))
                (let ((|Γc1003| (svref (cdr |_pL#k|) 1)))
                  (let ((|ρc1004| (cons |pair3| |Γc1003|)))
                    (funcall |_code1002| |ρc1004| |k|)))))))))))

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (let ((|Γ| (cons '|𝐄| (vector |_pL#x|))))
        (let ((|lam5| (cons '|𝐂| (vector #'|fn1001| |Γ|))))
          (let ((|con6| (cons '|Cont| (vector |lam5|))))
            (funcall |k| |con6|)))))))

(defun |fn1005| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#c| (car |α|)))
      (let ((|_pR#c| (cdr |α|)))
        (cond
          ((eq (car |_pL#c|) '|Cont|)
            (let ((|p10| (svref (cdr |_pL#c|) 0)))
              (let ((|u11| nil))
                (let ((|pair12| (cons |_pR#c| |u11|)))
                  (let ((|_code1006| (svref (cdr |p10|) 0)))
                    (let ((|Γc1007| (svref (cdr |p10|) 1)))
                      (let ((|ρc1008| (cons |pair12| |Γc1007|)))
                        (funcall |_code1006| |ρc1008| |k|)))))))))))))

(defun |fn1011| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pR#?x₀| (svref (cdr |Γ|) 1)))
        (let ((|_pL#k| (svref (cdr |Γ|) 0)))
          (let ((|_pL#a| (car |α|)))
            (let ((|u20| nil))
              (let ((|pair21| (cons |_pL#a| |u20|)))
                (let ((|_code1015| (svref (cdr |_pR#?x₀|) 0)))
                  (let ((|Γc1016| (svref (cdr |_pR#?x₀|) 1)))
                    (let ((|ρc1017| (cons |pair21| |Γc1016|)))
                      (labels ((|k1| (|v0|)
                        (cond
                          ((eq (car |v0|) '|Cont|)
                            (let ((|p24| (svref (cdr |v0|) 0)))
                              (let ((|u25| nil))
                                (let ((|pair26| (cons |_pL#k| |u25|)))
                                  (let ((|_code1012| (svref (cdr |p24|) 0)))
                                    (let ((|Γc1013| (svref (cdr |p24|) 1)))
                                      (let ((|ρc1014| (cons |pair26| |Γc1013|)))
                                        (funcall |_code1012| |ρc1014| |k|)))))))))))
                        (funcall |_code1015| |ρc1017| #'|k1|)))))))))))))

(defun |fn1010| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|p17| (svref (cdr |Γ|) 1)))
        (let ((|_pR#?x₀| (svref (cdr |Γ|) 0)))
          (let ((|_pL#k| (car |α|)))
            (let ((|Γ| (cons '|𝐄| (vector |_pL#k| |_pR#?x₀|))))
              (let ((|lam28| (cons '|𝐂| (vector #'|fn1011| |Γ|))))
                (let ((|u29| nil))
                  (let ((|pair30| (cons |lam28| |u29|)))
                    (let ((|_code1018| (svref (cdr |p17|) 0)))
                      (let ((|Γc1019| (svref (cdr |p17|) 1)))
                        (let ((|ρc1020| (cons |pair30| |Γc1019|)))
                          (funcall |_code1018| |ρc1020| |k|))))))))))))))

(defun |fn1009| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|_pR#?x₀| (cdr |α|)))
        (cond
          ((eq (car |_pL#?x₀|) '|Cont|)
            (let ((|p17| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|Γ| (cons '|𝐄| (vector |_pR#?x₀| |p17|))))
                (let ((|lam32| (cons '|𝐂| (vector #'|fn1010| |Γ|))))
                  (let ((|con33| (cons '|Cont| (vector |lam32|))))
                    (funcall |k| |con33|)))))))))))

(defun |fn1024| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cdr |payload|)))
    (let ((|_pL#k| (svref (cdr |Γ|) 1)))
      (let ((|_pL#a| (svref (cdr |Γ|) 0)))
        (let ((|u39| nil))
          (let ((|pair40| (cons |_pL#a| |u39|)))
            (let ((|_code1025| (svref (cdr |_pL#k|) 0)))
              (let ((|Γc1026| (svref (cdr |_pL#k|) 1)))
                (let ((|ρc1027| (cons |pair40| |Γc1026|)))
                  (funcall |_code1025| |ρc1027| |k|))))))))))

(defun |fn1023| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#k| (svref (cdr |Γ|) 0)))
        (let ((|_pL#a| (car |α|)))
          (let ((|Γ| (cons '|𝐄| (vector |_pL#a| |_pL#k|))))
            (let ((|lam42| (cons '|𝐂| (vector #'|fn1024| |Γ|))))
              (let ((|con43| (cons '|Cont| (vector |lam42|))))
                (funcall |k| |con43|)))))))))

(defun |fn1022| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#f| (svref (cdr |Γ|) 0)))
        (let ((|_pL#k| (car |α|)))
          (let ((|Γ| (cons '|𝐄| (vector |_pL#k|))))
            (let ((|lam44| (cons '|𝐂| (vector #'|fn1023| |Γ|))))
              (let ((|u45| nil))
                (let ((|pair46| (cons |lam44| |u45|)))
                  (let ((|_code1031| (svref (cdr |_pL#f|) 0)))
                    (let ((|Γc1032| (svref (cdr |_pL#f|) 1)))
                      (let ((|ρc1033| (cons |pair46| |Γc1032|)))
                        (labels ((|k3| (|v2|)
                          (cond
                            ((eq (car |v2|) '|Cont|)
                              (let ((|p49| (svref (cdr |v2|) 0)))
                                (let ((|u50| nil))
                                  (let ((|pair51| (cons |_pL#k| |u50|)))
                                    (let ((|_code1028| (svref (cdr |p49|) 0)))
                                      (let ((|Γc1029| (svref (cdr |p49|) 1)))
                                        (let ((|ρc1030| (cons |pair51| |Γc1029|)))
                                          (funcall |_code1028| |ρc1030| |k|)))))))))))
                          (funcall |_code1031| |ρc1033| #'|k3|))))))))))))))

(defun |fn1021| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#f| (car |α|)))
      (let ((|Γ| (cons '|𝐄| (vector |_pL#f|))))
        (let ((|lam53| (cons '|𝐂| (vector #'|fn1022| |Γ|))))
          (let ((|con54| (cons '|Cont| (vector |lam53|))))
            (funcall |k| |con54|)))))))

(defun |fn1035| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cdr |payload|)))
    (let ((|_pL#k| (svref (cdr |Γ|) 0)))
      (let ((|c62| 42))
        (let ((|u63| nil))
          (let ((|pair64| (cons |c62| |u63|)))
            (let ((|_code1036| (svref (cdr |_pL#k|) 0)))
              (let ((|Γc1037| (svref (cdr |_pL#k|) 1)))
                (let ((|ρc1038| (cons |pair64| |Γc1037|)))
                  (funcall |_code1036| |ρc1038| |k|))))))))))

(defun |fn1034| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam7| (svref (cdr |Γ|) 1)))
        (let ((|lam34| (svref (cdr |Γ|) 0)))
          (let ((|_pL#k| (car |α|)))
            (let ((|c57| 0))
              (let ((|u58| nil))
                (let ((|pair59| (cons |c57| |u58|)))
                  (let ((|_code1042| (svref (cdr |lam7|) 0)))
                    (let ((|Γc1043| (svref (cdr |lam7|) 1)))
                      (let ((|ρc1044| (cons |pair59| |Γc1043|)))
                        (labels ((|k5| (|v4|)
                          (let ((|Γ| (cons '|𝐄| (vector |_pL#k|))))
                            (let ((|lam66| (cons '|𝐂| (vector #'|fn1035| |Γ|))))
                              (let ((|pair67| (cons |v4| |lam66|)))
                                (let ((|_code1039| (svref (cdr |lam34|) 0)))
                                  (let ((|Γc1040| (svref (cdr |lam34|) 1)))
                                    (let ((|ρc1041| (cons |pair67| |Γc1040|)))
                                      (funcall |_code1039| |ρc1041| |k|)))))))))
                          (funcall |_code1042| |ρc1044| #'|k5|))))))))))))))

(defun |fn1048| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (funcall |k| |_pL#x|))))

; entrypoint
(defun |main| (|arg| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|lam7| (cons '|𝐂| (vector #'|fn1000| |Γ|))))
      (let ((|Γ| (cons '|𝐄| (vector))))
        (let ((|lam14| (cons '|𝐂| (vector #'|fn1005| |Γ|))))
          (let ((|Γ| (cons '|𝐄| (vector))))
            (let ((|lam34| (cons '|𝐂| (vector #'|fn1009| |Γ|))))
              (let ((|Γ| (cons '|𝐄| (vector |lam34| |lam7|))))
                (let ((|lam69| (cons '|𝐂| (vector #'|fn1034| |Γ|))))
                  (let ((|u70| nil))
                    (let ((|pair71| (cons |lam69| |u70|)))
                      (let ((|ρc1047| (cons |pair71| |Γ|)))
                        (labels ((|k7| (|v6|)
                          (let ((|Γ| (cons '|𝐄| (vector))))
                            (let ((|lam74| (cons '|𝐂| (vector #'|fn1048| |Γ|))))
                              (let ((|pair75| (cons |v6| |lam74|)))
                                (let ((|_code1049| (svref (cdr |lam14|) 0)))
                                  (let ((|Γc1050| (svref (cdr |lam14|) 1)))
                                    (let ((|ρc1051| (cons |pair75| |Γc1050|)))
                                      (funcall |_code1049| |ρc1051| |k|)))))))))
                          (funcall #'|fn1021| |ρc1047| #'|k7|))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

