;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |go| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#n| (svref (cdr |Γ|) 3)))
        (let ((|%to-string| (svref (cdr |Γ|) 2)))
          (let ((|%string-append| (svref (cdr |Γ|) 1)))
            (let ((|%println| (svref (cdr |Γ|) 0)))
              (let ((|_pL#acc| (car |α|)))
                (let ((|_pR#acc| (cdr |α|)))
                  (cond
                    ((equal |_pR#acc| 0)
                      (funcall |k| |_pL#acc|))
                    (t
                      (let ((|p2| (tigris-ffi:%int* |_pL#acc| |_pR#acc|)))
                        (let ((|c3| "fact "))
                          (let ((|p4| (tigris-ffi:%int- |_pL#n| |_pR#acc|)))
                            (let ((|u5| nil))
                              (let ((|pair6| (cons |p4| |u5|)))
                                (let ((|_code1017| (svref (cdr |%to-string|) 0)))
                                  (let ((|Γc1018| (svref (cdr |%to-string|) 1)))
                                    (let ((|ρc1019| (cons |pair6| |Γc1018|)))
                                      (labels ((|k1| (|v0|)
                                        (let ((|pair8| (cons |c3| |v0|)))
                                          (let ((|_code1014| (svref (cdr |%string-append|) 0)))
                                            (let ((|Γc1015| (svref (cdr |%string-append|) 1)))
                                              (let ((|ρc1016| (cons |pair8| |Γc1015|)))
                                                (labels ((|k3| (|v2|)
                                                  (let ((|c10| " = "))
                                                    (let ((|pair11| (cons |v2| |c10|)))
                                                      (let ((|_code1011| (svref (cdr |%string-append|) 0)))
                                                        (let ((|Γc1012| (svref (cdr |%string-append|) 1)))
                                                          (let ((|ρc1013| (cons |pair11| |Γc1012|)))
                                                            (labels ((|k5| (|v4|)
                                                              (let ((|u13| nil))
                                                                (let ((|pair14| (cons |p2| |u13|)))
                                                                  (let ((|_code1008| (svref (cdr |%to-string|) 0)))
                                                                    (let ((|Γc1009| (svref (cdr |%to-string|) 1)))
                                                                      (let ((|ρc1010| (cons |pair14| |Γc1009|)))
                                                                        (labels ((|k7| (|v6|)
                                                                          (let ((|pair16| (cons |v4| |v6|)))
                                                                            (let ((|_code1005| (svref (cdr |%string-append|) 0)))
                                                                              (let ((|Γc1006| (svref (cdr |%string-append|) 1)))
                                                                                (let ((|ρc1007| (cons |pair16| |Γc1006|)))
                                                                                  (labels ((|k9| (|v8|)
                                                                                    (let ((|u18| nil))
                                                                                      (let ((|pair19| (cons |v8| |u18|)))
                                                                                        (let ((|_code1002| (svref (cdr |%println|) 0)))
                                                                                          (let ((|Γc1003| (svref (cdr |%println|) 1)))
                                                                                            (let ((|ρc1004| (cons |pair19| |Γc1003|)))
                                                                                              (labels ((|k11| (|v10|)
                                                                                                (let ((|c21| 1))
                                                                                                  (let ((|p22| (tigris-ffi:%int- |_pR#acc| |c21|)))
                                                                                                    (let ((|pair23| (cons |p2| |p22|)))
                                                                                                      (let ((|ρ1001| (cons |pair23| |Γ|)))
                                                                                                        (funcall #'|go| |ρ1001| |k|)))))))
                                                                                                (funcall |_code1002| |ρc1004| #'|k11|)))))))))
                                                                                    (funcall |_code1005| |ρc1007| #'|k9|))))))))
                                                                          (funcall |_code1008| |ρc1010| #'|k7|)))))))))
                                                              (funcall |_code1011| |ρc1013| #'|k5|)))))))))
                                                  (funcall |_code1014| |ρc1016| #'|k3|))))))))
                                        (funcall |_code1017| |ρc1019| #'|k1|)))))))))))))))))))))

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|%to-string| (svref (cdr |Γ|) 2)))
        (let ((|%string-append| (svref (cdr |Γ|) 1)))
          (let ((|%println| (svref (cdr |Γ|) 0)))
            (let ((|_pL#n| (car |α|)))
              (let ((|Γ| (cons '|𝐄| (vector |%println| |%string-append| |%to-string| |_pL#n|))))
                (let ((|go#clo1023| (cons '|𝐂| (vector #'|go| |Γ|))))
                  (let ((|c25| 1))
                    (let ((|pair26| (cons |c25| |_pL#n|)))
                      (let ((|_code1020| (svref (cdr |go#clo1023|) 0)))
                        (let ((|Γc1021| (svref (cdr |go#clo1023|) 1)))
                          (let ((|ρc1022| (cons |pair26| |Γc1021|)))
                            (funcall |_code1020| |ρc1022| |k|)))))))))))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector |%println| |%string-append| |%to-string|))))
    (let ((|lam28| (cons '|𝐂| (vector #'|fn1000| |Γ|))))
      (let ((|c29| 5))
        (let ((|u30| nil))
          (let ((|pair31| (cons |c29| |u30|)))
            (let ((|_code1024| (svref (cdr |lam28|) 0)))
              (let ((|Γc1025| (svref (cdr |lam28|) 1)))
                (let ((|ρc1026| (cons |pair31| |Γc1025|)))
                  (funcall |_code1024| |ρc1026| |k|))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

