;; == Runtime ==
(load "runtime.lisp")

;; == Linked Lisp Source ==
(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |go| (|payload1006| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1006|))
  (let ((|α1007| (car |payload1006|)))
  (let ((|Γ1008| (cdr |payload1006|)))
  (let ((|_pL#n| (svref (cdr |Γ1008|) 3)))
  (let ((|%to-string| (svref (cdr |Γ1008|) 2)))
  (let ((|%string-append| (svref (cdr |Γ1008|) 1)))
  (let ((|%println| (svref (cdr |Γ1008|) 0)))
  (let ((|_pL#acc| (car |α1007|)))
  (let ((|_pR#acc| (cdr |α1007|)))
  (cond
    ((equal |_pR#acc| 0)
      (funcall (the function |k|) |_pL#acc|))
    (t
      (let ((|p2| (%int* |_pL#acc| |_pR#acc|)))
        (let ((|c3| "fact "))
        (let ((|p4| (%int- |_pL#n| |_pR#acc|)))
        (let ((|u5| nil))
        (let ((|pair6| (cons |p4| |u5|)))
        (let ((|_code1025| (svref (cdr |%to-string|) 0)))
        (let ((|Γc1026| (svref (cdr |%to-string|) 1)))
        (let ((|ρc1027| (cons |pair6| |Γc1026|)))
        (labels
          ((|k1| (|v0|)
            (let ((|pair8| (cons |c3| |v0|)))
            (let ((|_code1022| (svref (cdr |%string-append|) 0)))
            (let ((|Γc1023| (svref (cdr |%string-append|) 1)))
            (let ((|ρc1024| (cons |pair8| |Γc1023|)))
            (labels
              ((|k3| (|v2|)
                (let ((|c10| " = "))
                (let ((|pair11| (cons |v2| |c10|)))
                (let ((|_code1019| (svref (cdr |%string-append|) 0)))
                (let ((|Γc1020| (svref (cdr |%string-append|) 1)))
                (let ((|ρc1021| (cons |pair11| |Γc1020|)))
                (labels
                  ((|k5| (|v4|)
                    (let ((|u13| nil))
                    (let ((|pair14| (cons |p2| |u13|)))
                    (let ((|_code1016| (svref (cdr |%to-string|) 0)))
                    (let ((|Γc1017| (svref (cdr |%to-string|) 1)))
                    (let ((|ρc1018| (cons |pair14| |Γc1017|)))
                    (labels
                      ((|k7| (|v6|)
                        (let ((|pair16| (cons |v4| |v6|)))
                        (let ((|_code1013| (svref (cdr |%string-append|) 0)))
                        (let ((|Γc1014| (svref (cdr |%string-append|) 1)))
                        (let ((|ρc1015| (cons |pair16| |Γc1014|)))
                        (labels
                          ((|k9| (|v8|)
                            (let ((|u18| nil))
                            (let ((|pair19| (cons |v8| |u18|)))
                            (let ((|_code1010| (svref (cdr |%println|) 0)))
                            (let ((|Γc1011| (svref (cdr |%println|) 1)))
                            (let ((|ρc1012| (cons |pair19| |Γc1011|)))
                            (labels
                              ((|k11| (|v10|)
                                (let ((|c21| 1))
                                (let ((|p22| (%int- |_pR#acc| |c21|)))
                                (let ((|pair23| (cons |p2| |p22|)))
                                (let ((|ρ1009| (cons |pair23| |Γ1008|)))
                                (funcall #'|go| |ρ1009| |k|)))))))
                              (funcall (the function |_code1010|) |ρc1012| #'|k11|)))))))))
                          (funcall (the function |_code1013|) |ρc1015| #'|k9|))))))))
                      (funcall (the function |_code1016|) |ρc1018| #'|k7|)))))))))
                  (funcall (the function |_code1019|) |ρc1021| #'|k5|)))))))))
              (funcall (the function |_code1022|) |ρc1024| #'|k3|))))))))
          (funcall (the function |_code1025|) |ρc1027| #'|k1|)))))))))))))))))))))

(defun |fn1003| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1004| (car |payload|)))
  (let ((|Γ1005| (cdr |payload|)))
  (let ((|%to-string| (svref (cdr |Γ1005|) 2)))
  (let ((|%string-append| (svref (cdr |Γ1005|) 1)))
  (let ((|%println| (svref (cdr |Γ1005|) 0)))
  (let ((|_pL#n| (car |α1004|)))
  (let ((|Γ1032| (cons '|𝐄| (vector |%println| |%string-append| |%to-string| |_pL#n|))))
  (let ((|go#clo1031| (cons '|𝐂| (vector #'|go| |Γ1032|))))
  (let ((|c25| 1))
  (let ((|pair26| (cons |c25| |_pL#n|)))
  (let ((|_code1028| (svref (cdr |go#clo1031|) 0)))
  (let ((|Γc1029| (svref (cdr |go#clo1031|) 1)))
  (let ((|ρc1030| (cons |pair26| |Γc1029|)))
  (funcall (the function |_code1028|) |ρc1030| |k|)))))))))))))))

; entrypoint
(defun |main| (|payload1000| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1000|))
  (let ((|Γ1042| (cons '|𝐄| (vector |%println| |%string-append| |%to-string|))))
  (let ((|lam28| (cons '|𝐂| (vector #'|fn1003| |Γ1042|))))
  (let ((|c29| "Enter a number:"))
  (let ((|u30| nil))
  (let ((|pair31| (cons |c29| |u30|)))
  (let ((|_code1039| (svref (cdr |%println|) 0)))
  (let ((|Γc1040| (svref (cdr |%println|) 1)))
  (let ((|ρc1041| (cons |pair31| |Γc1040|)))
  (labels
    ((|k13| (|v12|)
      (let ((|c33| nil))
      (let ((|u34| nil))
      (let ((|pair35| (cons |c33| |u34|)))
      (let ((|_code1036| (svref (cdr |%read|) 0)))
      (let ((|Γc1037| (svref (cdr |%read|) 1)))
      (let ((|ρc1038| (cons |pair35| |Γc1037|)))
      (labels
        ((|k15| (|v14|)
          (let ((|u37| nil))
          (let ((|pair38| (cons |v14| |u37|)))
          (let ((|_code1033| (svref (cdr |lam28|) 0)))
          (let ((|Γc1034| (svref (cdr |lam28|) 1)))
          (let ((|ρc1035| (cons |pair38| |Γc1034|)))
          (funcall (the function |_code1033|) |ρc1035| |k|))))))))
        (funcall (the function |_code1036|) |ρc1038| #'|k15|))))))))))
    (funcall (the function |_code1039|) |ρc1041| #'|k13|)))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

