;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |go| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#n| (svref (cdr |Γ|) 3)))
        (let ((|%to-string| (svref (cdr |Γ|) 2)))
          (let ((|%string-append| (svref (cdr |Γ|) 1)))
            (let ((|%println| (svref (cdr |Γ|) 0)))
              (let ((|_pL#acc| (car |α|)))
                (let ((|_pR#acc| (cdr |α|)))
                  (cond
                    ((equal |_pR#acc| 0)
                      (funcall |k| |_pL#acc|))
                    (t
                      (let ((|p3| (* |_pL#acc| |_pR#acc|)))
                        (let ((|c4| "fact "))
                          (let ((|p5| (- |_pL#n| |_pR#acc|)))
                            (let ((|u6| nil))
                              (let ((|pair7| (cons |p5| |u6|)))
                                (let ((|_code| (svref (cdr |%to-string|) 0)))
                                  (let ((|Γc| (svref (cdr |%to-string|) 1)))
                                    (let ((|ρc| (cons |pair7| |Γc|)))
                                      (labels ((|k1| (|v0|)
                                        (let ((|pair9| (cons |c4| |v0|)))
                                          (let ((|_code| (svref (cdr |%string-append|) 0)))
                                            (let ((|Γc| (svref (cdr |%string-append|) 1)))
                                              (let ((|ρc| (cons |pair9| |Γc|)))
                                                (labels ((|k3| (|v2|)
                                                  (let ((|c11| " = "))
                                                    (let ((|pair12| (cons |v2| |c11|)))
                                                      (let ((|_code| (svref (cdr |%string-append|) 0)))
                                                        (let ((|Γc| (svref (cdr |%string-append|) 1)))
                                                          (let ((|ρc| (cons |pair12| |Γc|)))
                                                            (labels ((|k5| (|v4|)
                                                              (let ((|u14| nil))
                                                                (let ((|pair15| (cons |p3| |u14|)))
                                                                  (let ((|_code| (svref (cdr |%to-string|) 0)))
                                                                    (let ((|Γc| (svref (cdr |%to-string|) 1)))
                                                                      (let ((|ρc| (cons |pair15| |Γc|)))
                                                                        (labels ((|k7| (|v6|)
                                                                          (let ((|pair17| (cons |v4| |v6|)))
                                                                            (let ((|_code| (svref (cdr |%string-append|) 0)))
                                                                              (let ((|Γc| (svref (cdr |%string-append|) 1)))
                                                                                (let ((|ρc| (cons |pair17| |Γc|)))
                                                                                  (labels ((|k9| (|v8|)
                                                                                    (let ((|u19| nil))
                                                                                      (let ((|pair20| (cons |v8| |u19|)))
                                                                                        (let ((|_code| (svref (cdr |%println|) 0)))
                                                                                          (let ((|Γc| (svref (cdr |%println|) 1)))
                                                                                            (let ((|ρc| (cons |pair20| |Γc|)))
                                                                                              (labels ((|k11| (|v10|)
                                                                                                (let ((|c22| 1))
                                                                                                  (let ((|p23| (- |_pR#acc| |c22|)))
                                                                                                    (let ((|pair24| (cons |p3| |p23|)))
                                                                                                      (let ((|ρ| (cons |pair24| |Γ|)))
                                                                                                        (funcall #'|go| |ρ| |k|)))))))
                                                                                                (funcall |_code| |ρc| #'|k11|)))))))))
                                                                                    (funcall |_code| |ρc| #'|k9|))))))))
                                                                          (funcall |_code| |ρc| #'|k7|)))))))))
                                                              (funcall |_code| |ρc| #'|k5|)))))))))
                                                  (funcall |_code| |ρc| #'|k3|))))))))
                                        (funcall |_code| |ρc| #'|k1|)))))))))))))))))))))

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|%to-string| (svref (cdr |Γ|) 2)))
        (let ((|%string-append| (svref (cdr |Γ|) 1)))
          (let ((|%println| (svref (cdr |Γ|) 0)))
            (let ((|_pL#n| (car |α|)))
              (let ((|Γ| (cons '|𝐄| (vector |%println| |%string-append| |%to-string| |_pL#n|))))
                (let ((|go| (cons '|𝐂| (vector #'|go| |Γ|))))
                  (let ((|c26| 1))
                    (let ((|pair27| (cons |c26| |_pL#n|)))
                      (let ((|_code| (svref (cdr |go|) 0)))
                        (let ((|Γc| (svref (cdr |go|) 1)))
                          (let ((|ρc| (cons |pair27| |Γc|)))
                            (funcall |_code| |ρc| |k|)))))))))))))))

; entrypoint
(defun |main| (|arg| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector |%println| |%string-append| |%to-string|))))
    (let ((|lam29| (cons '|𝐂| (vector #'|fn1000| |Γ|))))
      (let ((|c30| 5))
        (let ((|u31| nil))
          (let ((|pair32| (cons |c30| |u31|)))
            (let ((|_code| (svref (cdr |lam29|) 0)))
              (let ((|Γc| (svref (cdr |lam29|) 1)))
                (let ((|ρc| (cons |pair32| |Γc|)))
                  (funcall |_code| |ρc| |k|))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

