;; == Runtime ==
(load "runtime.lisp")

;; == Linked Lisp Source ==
(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |map| (|payload1003| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1003|))
  (let ((|α1004| (car |payload1003|)))
    (let ((|Γ1005| (cdr |payload1003|)))
      (let ((|_pL#f| (car |α1004|)))
        (let ((|_pR#f| (cdr |α1004|)))
          (cond
            ((eq (car |_pR#f|) '|Nil|)
              (let ((|con1| (cons '|Nil| (vector))))
                (funcall (the function |k|) |con1|)))
            ((eq (car |_pR#f|) '|Cons|)
              (let ((|p2| (svref (cdr |_pR#f|) 0)))
                (let ((|p3| (svref (cdr |_pR#f|) 1)))
                  (let ((|u4| nil))
                    (let ((|pair5| (cons |p2| |u4|)))
                      (let ((|_code1007| (svref (cdr |_pL#f|) 0)))
                        (let ((|Γc1008| (svref (cdr |_pL#f|) 1)))
                          (let ((|ρc1009| (cons |pair5| |Γc1008|)))
                            (labels ((|k1| (|v0|)
                              (let ((|pair7| (cons |_pL#f| |p3|)))
                                (let ((|ρ1006| (cons |pair7| |Γ1005|)))
                                  (labels ((|k3| (|v2|)
                                    (let ((|con9| (cons '|Cons| (vector |v0| |v2|))))
                                      (funcall (the function |k|) |con9|))))
                                    (funcall #'|map| |ρ1006| #'|k3|))))))
                              (funcall (the function |_code1007|) |ρc1009| #'|k1|))))))))))))))))

(defun |foldl| (|payload1010| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1010|))
  (let ((|α1011| (car |payload1010|)))
    (let ((|Γ1012| (cdr |payload1010|)))
      (let ((|_pL#f| (car |α1011|)))
        (let ((|_pR#f| (cdr |α1011|)))
          (let ((|_pL#init| (car |_pR#f|)))
            (let ((|_pR#init| (cdr |_pR#f|)))
              (cond
                ((eq (car |_pR#init|) '|Nil|)
                  (funcall (the function |k|) |_pL#init|))
                ((eq (car |_pR#init|) '|Cons|)
                  (let ((|p11| (svref (cdr |_pR#init|) 0)))
                    (let ((|p12| (svref (cdr |_pR#init|) 1)))
                      (let ((|pair13| (cons |_pL#init| |p11|)))
                        (let ((|_code1014| (svref (cdr |_pL#f|) 0)))
                          (let ((|Γc1015| (svref (cdr |_pL#f|) 1)))
                            (let ((|ρc1016| (cons |pair13| |Γc1015|)))
                              (labels ((|k5| (|v4|)
                                (let ((|pair16| (cons |v4| |p12|)))
                                  (let ((|pair15| (cons |_pL#f| |pair16|)))
                                    (let ((|ρ1013| (cons |pair15| |Γ1012|)))
                                      (funcall #'|foldl| |ρ1013| |k|))))))
                                (funcall (the function |_code1014|) |ρc1016| #'|k5|)))))))))))))))))

(defun |fn1017| (|payload1018| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1018|))
  (let ((|α1019| (car |payload1018|)))
    (let ((|_pL#?x₀| (car |α1019|)))
      (cond
        ((eq (car |_pL#?x₀|) '|Cons|)
          (let ((|p19| (svref (cdr |_pL#?x₀|) 0)))
            (funcall (the function |k|) |p19|)))
        (t
          (error +NOMATCH+ :discr "#[?x₀]"))))))

(defun |fn1021| (|payload1022| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1022|))
  (let ((|α1023| (car |payload1022|)))
    (let ((|_pL#?x₀| (car |α1023|)))
      (let ((|c34| 1))
        (let ((|p35| (%int+ |c34| |_pL#?x₀|)))
          (funcall (the function |k|) |p35|))))))

(defun |fn1028| (|payload1029| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1029|))
  (let ((|α1030| (car |payload1029|)))
    (let ((|_pL#?x₀| (car |α1030|)))
      (let ((|_pR#?x₀| (cdr |α1030|)))
        (let ((|p40| (%int+ |_pL#?x₀| |_pR#?x₀|)))
          (funcall (the function |k|) |p40|))))))

(defun |fn1035| (|payload1036| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1036|))
  (let ((|α1037| (car |payload1036|)))
    (let ((|_pL#?x₀| (car |α1037|)))
      (let ((|_pR#?x₀| (cdr |α1037|)))
        (let ((|p47| (%int+ |_pL#?x₀| |_pR#?x₀|)))
          (funcall (the function |k|) |p47|))))))

; entrypoint
(defun |main| (|payload1000| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1000|))
  (let ((|Γ1052| (cons '|𝐄| (vector))))
    (let ((|Γ1050| (cons '|𝐄| (vector))))
      (let ((|Γ1048| (cons '|𝐄| (vector))))
        (let ((|c24| 1))
          (let ((|c25| 2))
            (let ((|c26| 3))
              (let ((|c27| 4))
                (let ((|con28| (cons '|Nil| (vector))))
                  (let ((|con29| (cons '|Cons| (vector |c27| |con28|))))
                    (let ((|con30| (cons '|Cons| (vector |c26| |con29|))))
                      (let ((|con31| (cons '|Cons| (vector |c25| |con30|))))
                        (let ((|con32| (cons '|Cons| (vector |c24| |con31|))))
                          (let ((|Γ1047| (cons '|𝐄| (vector))))
                            (let ((|lam36| (cons '|𝐂| (vector #'|fn1021| |Γ1047|))))
                              (let ((|pair37| (cons |lam36| |con32|)))
                                (let ((|ρc1027| (cons |pair37| |Γ1052|)))
                                  (labels ((|k7| (|v6|)
                                    (let ((|Γ1046| (cons '|𝐄| (vector))))
                                      (let ((|lam41| (cons '|𝐂| (vector #'|fn1028| |Γ1046|))))
                                        (let ((|c42| 0))
                                          (let ((|pair44| (cons |c42| |con32|)))
                                            (let ((|pair43| (cons |lam41| |pair44|)))
                                              (let ((|ρc1034| (cons |pair43| |Γ1050|)))
                                                (labels ((|k9| (|v8|)
                                                  (let ((|Γ1045| (cons '|𝐄| (vector))))
                                                    (let ((|lam48| (cons '|𝐂| (vector #'|fn1035| |Γ1045|))))
                                                      (let ((|c49| 0))
                                                        (let ((|pair51| (cons |c49| |v6|)))
                                                          (let ((|pair50| (cons |lam48| |pair51|)))
                                                            (let ((|ρc1041| (cons |pair50| |Γ1050|)))
                                                              (labels ((|k11| (|v10|)
                                                                (let ((|u53| nil))
                                                                  (let ((|pair54| (cons |v6| |u53|)))
                                                                    (let ((|ρc1044| (cons |pair54| |Γ1048|)))
                                                                      (labels ((|k13| (|v12|)
                                                                        (let ((|p56| (cons |v10| |v12|)))
                                                                          (let ((|p57| (cons |v8| |p56|)))
                                                                            (let ((|p58| (cons |v6| |p57|)))
                                                                              (funcall (the function |k|) |p58|))))))
                                                                        (funcall #'|fn1017| |ρc1044| #'|k13|)))))))
                                                                (funcall #'|foldl| |ρc1041| #'|k11|))))))))))
                                                  (funcall #'|foldl| |ρc1034| #'|k9|))))))))))
                                    (funcall #'|map| |ρc1027| #'|k7|)))))))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

