;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |map| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#f| (car |α|)))
        (let ((|_pR#f| (cdr |α|)))
          (cond
            ((eq (car |_pR#f|) '|Nil|)
              (let ((|con1| (cons '|Nil| (vector))))
                (funcall |k| |con1|)))
            ((eq (car |_pR#f|) '|Cons|)
              (let ((|p2| (svref (cdr |_pR#f|) 0)))
                (let ((|p3| (svref (cdr |_pR#f|) 1)))
                  (let ((|u4| nil))
                    (let ((|pair5| (cons |p2| |u4|)))
                      (let ((|_code1001| (svref (cdr |_pL#f|) 0)))
                        (let ((|Γc1002| (svref (cdr |_pL#f|) 1)))
                          (let ((|ρc1003| (cons |pair5| |Γc1002|)))
                            (labels ((|k1| (|v0|)
                              (let ((|pair7| (cons |_pL#f| |p3|)))
                                (let ((|ρ1000| (cons |pair7| |Γ|)))
                                  (labels ((|k3| (|v2|)
                                    (let ((|con9| (cons '|Cons| (vector |v0| |v2|))))
                                      (funcall |k| |con9|))))
                                    (funcall #'|map| |ρ1000| #'|k3|))))))
                              (funcall |_code1001| |ρc1003| #'|k1|))))))))))))))))

(defun |foldl| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#f| (car |α|)))
        (let ((|_pR#f| (cdr |α|)))
          (let ((|_pL#init| (car |_pR#f|)))
            (let ((|_pR#init| (cdr |_pR#f|)))
              (cond
                ((eq (car |_pR#init|) '|Nil|)
                  (funcall |k| |_pL#init|))
                ((eq (car |_pR#init|) '|Cons|)
                  (let ((|p11| (svref (cdr |_pR#init|) 0)))
                    (let ((|p12| (svref (cdr |_pR#init|) 1)))
                      (let ((|pair13| (cons |_pL#init| |p11|)))
                        (let ((|_code1005| (svref (cdr |_pL#f|) 0)))
                          (let ((|Γc1006| (svref (cdr |_pL#f|) 1)))
                            (let ((|ρc1007| (cons |pair13| |Γc1006|)))
                              (labels ((|k5| (|v4|)
                                (let ((|pair16| (cons |v4| |p12|)))
                                  (let ((|pair15| (cons |_pL#f| |pair16|)))
                                    (let ((|ρ1004| (cons |pair15| |Γ|)))
                                      (funcall #'|foldl| |ρ1004| |k|))))))
                                (funcall |_code1005| |ρc1007| #'|k5|)))))))))))))))))

(defun |fn1008| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (cond
        ((eq (car |_pL#?x₀|) '|Cons|)
          (let ((|p19| (svref (cdr |_pL#?x₀|) 0)))
            (funcall |k| |p19|)))
        (t
          (error +NOMATCH+ :discr "#[?x₀]"))))))

(defun |fn1009| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|c34| 1))
        (let ((|p35| (%int+ |c34| |_pL#?x₀|)))
          (funcall |k| |p35|))))))

(defun |fn1013| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|_pR#?x₀| (cdr |α|)))
        (let ((|p40| (%int+ |_pL#?x₀| |_pR#?x₀|)))
          (funcall |k| |p40|))))))

(defun |fn1017| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|_pR#?x₀| (cdr |α|)))
        (let ((|p47| (%int+ |_pL#?x₀| |_pR#?x₀|)))
          (funcall |k| |p47|))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|c24| 1))
    (let ((|c25| 2))
      (let ((|c26| 3))
        (let ((|c27| 4))
          (let ((|con28| (cons '|Nil| (vector))))
            (let ((|con29| (cons '|Cons| (vector |c27| |con28|))))
              (let ((|con30| (cons '|Cons| (vector |c26| |con29|))))
                (let ((|con31| (cons '|Cons| (vector |c25| |con30|))))
                  (let ((|con32| (cons '|Cons| (vector |c24| |con31|))))
                    (let ((|Γ| (cons '|𝐄| (vector))))
                      (let ((|lam36| (cons '|𝐂| (vector #'|fn1009| |Γ|))))
                        (let ((|pair37| (cons |lam36| |con32|)))
                          (let ((|ρc1012| (cons |pair37| |Γ|)))
                            (labels ((|k7| (|v6|)
                              (let ((|Γ| (cons '|𝐄| (vector))))
                                (let ((|lam41| (cons '|𝐂| (vector #'|fn1013| |Γ|))))
                                  (let ((|c42| 0))
                                    (let ((|pair44| (cons |c42| |con32|)))
                                      (let ((|pair43| (cons |lam41| |pair44|)))
                                        (let ((|ρc1016| (cons |pair43| |Γ|)))
                                          (labels ((|k9| (|v8|)
                                            (let ((|Γ| (cons '|𝐄| (vector))))
                                              (let ((|lam48| (cons '|𝐂| (vector #'|fn1017| |Γ|))))
                                                (let ((|c49| 0))
                                                  (let ((|pair51| (cons |c49| |v6|)))
                                                    (let ((|pair50| (cons |lam48| |pair51|)))
                                                      (let ((|ρc1020| (cons |pair50| |Γ|)))
                                                        (labels ((|k11| (|v10|)
                                                          (let ((|u53| nil))
                                                            (let ((|pair54| (cons |v6| |u53|)))
                                                              (let ((|ρc1023| (cons |pair54| |Γ|)))
                                                                (labels ((|k13| (|v12|)
                                                                  (let ((|p56| (cons |v10| |v12|)))
                                                                    (let ((|p57| (cons |v8| |p56|)))
                                                                      (let ((|p58| (cons |v6| |p57|)))
                                                                        (funcall |k| |p58|))))))
                                                                  (funcall #'|fn1008| |ρc1023| #'|k13|)))))))
                                                          (funcall #'|foldl| |ρc1020| #'|k11|))))))))))
                                            (funcall #'|foldl| |ρc1016| #'|k9|))))))))))
                              (funcall #'|map| |ρc1012| #'|k7|))))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

