;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |map| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#f| (car |α|)))
        (let ((|_pR#f| (cdr |α|)))
          (cond
            ((eq (car |_pR#f|) '|Nil|)
              (let ((|con2| (cons '|Nil| (vector))))
                (funcall |k| |con2|)))
            ((eq (car |_pR#f|) '|Cons|)
              (let ((|p3| (svref (cdr |_pR#f|) 0)))
                (let ((|p4| (svref (cdr |_pR#f|) 1)))
                  (let ((|u5| nil))
                    (let ((|pair6| (cons |p3| |u5|)))
                      (let ((|_code1001| (svref (cdr |_pL#f|) 0)))
                        (let ((|Γc1002| (svref (cdr |_pL#f|) 1)))
                          (let ((|ρc1003| (cons |pair6| |Γc1002|)))
                            (labels ((|k1| (|v0|)
                              (let ((|pair8| (cons |_pL#f| |p4|)))
                                (let ((|ρ1000| (cons |pair8| |Γ|)))
                                  (labels ((|k3| (|v2|)
                                    (let ((|con10| (cons '|Cons| (vector |v0| |v2|))))
                                      (funcall |k| |con10|))))
                                    (funcall #'|map| |ρ1000| #'|k3|))))))
                              (funcall |_code1001| |ρc1003| #'|k1|))))))))))))))))

(defun |foldl| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#f| (car |α|)))
        (let ((|_pR#f| (cdr |α|)))
          (let ((|_pL#init| (car |_pR#f|)))
            (let ((|_pR#init| (cdr |_pR#f|)))
              (cond
                ((eq (car |_pR#init|) '|Nil|)
                  (funcall |k| |_pL#init|))
                ((eq (car |_pR#init|) '|Cons|)
                  (let ((|p13| (svref (cdr |_pR#init|) 0)))
                    (let ((|p14| (svref (cdr |_pR#init|) 1)))
                      (let ((|pair15| (cons |_pL#init| |p13|)))
                        (let ((|_code1005| (svref (cdr |_pL#f|) 0)))
                          (let ((|Γc1006| (svref (cdr |_pL#f|) 1)))
                            (let ((|ρc1007| (cons |pair15| |Γc1006|)))
                              (labels ((|k5| (|v4|)
                                (let ((|pair18| (cons |v4| |p14|)))
                                  (let ((|pair17| (cons |_pL#f| |pair18|)))
                                    (let ((|ρ1004| (cons |pair17| |Γ|)))
                                      (funcall #'|foldl| |ρ1004| |k|))))))
                                (funcall |_code1005| |ρc1007| #'|k5|)))))))))))))))))

(defun |fn1008| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (cond
        ((eq (car |_pL#?x₀|) '|Cons|)
          (let ((|p22| (svref (cdr |_pL#?x₀|) 0)))
            (funcall |k| |p22|)))
        (t
          (let ((|u21| nil))
            (funcall |k| |u21|)))))))

(defun |fn1009| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|c38| 1))
        (let ((|p39| (+ |c38| |_pL#?x₀|)))
          (funcall |k| |p39|))))))

(defun |fn1013| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|_pR#?x₀| (cdr |α|)))
        (let ((|p44| (+ |_pL#?x₀| |_pR#?x₀|)))
          (funcall |k| |p44|))))))

(defun |fn1017| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|_pR#?x₀| (cdr |α|)))
        (let ((|p51| (+ |_pL#?x₀| |_pR#?x₀|)))
          (funcall |k| |p51|))))))

; entrypoint
(defun |main| (|arg| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|map| (cons '|𝐂| (vector #'|map| |Γ|))))
      (let ((|Γ| (cons '|𝐄| (vector))))
        (let ((|foldl| (cons '|𝐂| (vector #'|foldl| |Γ|))))
          (let ((|c28| 1))
            (let ((|c29| 2))
              (let ((|c30| 3))
                (let ((|c31| 4))
                  (let ((|con32| (cons '|Nil| (vector))))
                    (let ((|con33| (cons '|Cons| (vector |c31| |con32|))))
                      (let ((|con34| (cons '|Cons| (vector |c30| |con33|))))
                        (let ((|con35| (cons '|Cons| (vector |c29| |con34|))))
                          (let ((|con36| (cons '|Cons| (vector |c28| |con35|))))
                            (let ((|Γ| (cons '|𝐄| (vector))))
                              (let ((|lam40| (cons '|𝐂| (vector #'|fn1009| |Γ|))))
                                (let ((|pair41| (cons |lam40| |con36|)))
                                  (let ((|ρc1012| (cons |pair41| |Γ|)))
                                    (labels ((|k7| (|v6|)
                                      (let ((|Γ| (cons '|𝐄| (vector))))
                                        (let ((|lam45| (cons '|𝐂| (vector #'|fn1013| |Γ|))))
                                          (let ((|c46| 0))
                                            (let ((|pair48| (cons |c46| |con36|)))
                                              (let ((|pair47| (cons |lam45| |pair48|)))
                                                (let ((|ρc1016| (cons |pair47| |Γ|)))
                                                  (labels ((|k9| (|v8|)
                                                    (let ((|Γ| (cons '|𝐄| (vector))))
                                                      (let ((|lam52| (cons '|𝐂| (vector #'|fn1017| |Γ|))))
                                                        (let ((|c53| 0))
                                                          (let ((|pair55| (cons |c53| |v6|)))
                                                            (let ((|pair54| (cons |lam52| |pair55|)))
                                                              (let ((|ρc1020| (cons |pair54| |Γ|)))
                                                                (labels ((|k11| (|v10|)
                                                                  (let ((|u57| nil))
                                                                    (let ((|pair58| (cons |v6| |u57|)))
                                                                      (let ((|ρc1023| (cons |pair58| |Γ|)))
                                                                        (labels ((|k13| (|v12|)
                                                                          (let ((|p60| (cons |v10| |v12|)))
                                                                            (let ((|p61| (cons |v8| |p60|)))
                                                                              (let ((|p62| (cons |v6| |p61|)))
                                                                                (funcall |k| |p62|))))))
                                                                          (funcall #'|fn1008| |ρc1023| #'|k13|)))))))
                                                                  (funcall #'|foldl| |ρc1020| #'|k11|))))))))))
                                                    (funcall #'|foldl| |ρc1016| #'|k9|))))))))))
                                      (funcall #'|map| |ρc1012| #'|k7|))))))))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

