;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |countTree| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#?x₀| (car |α|)))
        (cond
          ((eq (car |_pL#?x₀|) '|Empty|)
            (let ((|c1| 0))
              (funcall (the function |k|) |c1|)))
          ((eq (car |_pL#?x₀|) '|Node|)
            (let ((|p2| (svref (cdr |_pL#?x₀|) 1)))
              (let ((|c3| 1))
                (let ((|u4| nil))
                  (let ((|pair5| (cons |p2| |u4|)))
                    (let ((|ρ1000| (cons |pair5| |Γ|)))
                      (labels ((|k1| (|v0|)
                        (let ((|p7| (%int+ |c3| |v0|)))
                          (funcall (the function |k|) |p7|))))
                        (funcall #'|countForest| |ρ1000| #'|k1|)))))))))))))

(defun |countForest| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#?x₀| (car |α|)))
        (cond
          ((eq (car |_pL#?x₀|) '|Nil|)
            (let ((|c9| 0))
              (funcall (the function |k|) |c9|)))
          ((eq (car |_pL#?x₀|) '|Cons|)
            (let ((|p10| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|p11| (svref (cdr |_pL#?x₀|) 1)))
                (let ((|u12| nil))
                  (let ((|pair13| (cons |p10| |u12|)))
                    (let ((|ρ1002| (cons |pair13| |Γ|)))
                      (labels ((|k3| (|v2|)
                        (let ((|u15| nil))
                          (let ((|pair16| (cons |p11| |u15|)))
                            (let ((|ρ1001| (cons |pair16| |Γ|)))
                              (labels ((|k5| (|v4|)
                                (let ((|p18| (%int+ |v2| |v4|)))
                                  (funcall (the function |k|) |p18|))))
                                (funcall #'|countForest| |ρ1001| #'|k5|)))))))
                        (funcall #'|countTree| |ρ1002| #'|k3|)))))))))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|countTree#clo1006| (cons '|𝐂| (vector #'|countTree| |Γ|))))
      (let ((|c19| 1))
        (let ((|c20| 2))
          (let ((|c21| 5))
            (let ((|con22| (cons '|Nil| (vector))))
              (let ((|con23| (cons '|Node| (vector |c21| |con22|))))
                (let ((|con24| (cons '|Nil| (vector))))
                  (let ((|con25| (cons '|Cons| (vector |con23| |con24|))))
                    (let ((|con26| (cons '|Node| (vector |c20| |con25|))))
                      (let ((|c27| 3))
                        (let ((|c28| 4))
                          (let ((|con29| (cons '|Nil| (vector))))
                            (let ((|con30| (cons '|Node| (vector |c28| |con29|))))
                              (let ((|con31| (cons '|Nil| (vector))))
                                (let ((|con32| (cons '|Cons| (vector |con30| |con31|))))
                                  (let ((|con33| (cons '|Node| (vector |c27| |con32|))))
                                    (let ((|con34| (cons '|Empty| (vector))))
                                      (let ((|con35| (cons '|Nil| (vector))))
                                        (let ((|con36| (cons '|Cons| (vector |con34| |con35|))))
                                          (let ((|con37| (cons '|Cons| (vector |con33| |con36|))))
                                            (let ((|con38| (cons '|Cons| (vector |con26| |con37|))))
                                              (let ((|con39| (cons '|Node| (vector |c19| |con38|))))
                                                (let ((|u40| nil))
                                                  (let ((|pair41| (cons |con39| |u40|)))
                                                    (let ((|_code1003| (svref (cdr |countTree#clo1006|) 0)))
                                                      (let ((|Γc1004| (svref (cdr |countTree#clo1006|) 1)))
                                                        (let ((|ρc1005| (cons |pair41| |Γc1004|)))
                                                          (funcall (the function |_code1003|) |ρc1005| |k|))))))))))))))))))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

