;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |countTree| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#?x₀| (car |α|)))
        (cond
          ((eq (car |_pL#?x₀|) '|Empty|)
            (let ((|c2| 0))
              (funcall |k| |c2|)))
          ((eq (car |_pL#?x₀|) '|Node|)
            (let ((|p3| (svref (cdr |_pL#?x₀|) 1)))
              (let ((|c4| 1))
                (let ((|u5| nil))
                  (let ((|pair6| (cons |p3| |u5|)))
                    (let ((|ρ1000| (cons |pair6| |Γ|)))
                      (labels ((|k1| (|v0|)
                        (let ((|p8| (sb-kernel:two-arg-+ |c4| |v0|)))
                          (funcall |k| |p8|))))
                        (funcall #'|countForest| |ρ1000| #'|k1|)))))))))))))

(defun |countForest| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#?x₀| (car |α|)))
        (cond
          ((eq (car |_pL#?x₀|) '|Nil|)
            (let ((|c11| 0))
              (funcall |k| |c11|)))
          ((eq (car |_pL#?x₀|) '|Cons|)
            (let ((|p12| (svref (cdr |_pL#?x₀|) 0)))
              (let ((|p13| (svref (cdr |_pL#?x₀|) 1)))
                (let ((|u14| nil))
                  (let ((|pair15| (cons |p12| |u14|)))
                    (let ((|ρ1002| (cons |pair15| |Γ|)))
                      (labels ((|k3| (|v2|)
                        (let ((|u17| nil))
                          (let ((|pair18| (cons |p13| |u17|)))
                            (let ((|ρ1001| (cons |pair18| |Γ|)))
                              (labels ((|k5| (|v4|)
                                (let ((|p20| (sb-kernel:two-arg-+ |v2| |v4|)))
                                  (funcall |k| |p20|))))
                                (funcall #'|countForest| |ρ1001| #'|k5|)))))))
                        (funcall #'|countTree| |ρ1002| #'|k3|)))))))))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|countTree#clo1006| (cons '|𝐂| (vector #'|countTree| |Γ|))))
      (let ((|c21| 1))
        (let ((|c22| 2))
          (let ((|c23| 5))
            (let ((|con24| (cons '|Nil| (vector))))
              (let ((|con25| (cons '|Node| (vector |c23| |con24|))))
                (let ((|con26| (cons '|Nil| (vector))))
                  (let ((|con27| (cons '|Cons| (vector |con25| |con26|))))
                    (let ((|con28| (cons '|Node| (vector |c22| |con27|))))
                      (let ((|c29| 3))
                        (let ((|c30| 4))
                          (let ((|con31| (cons '|Nil| (vector))))
                            (let ((|con32| (cons '|Node| (vector |c30| |con31|))))
                              (let ((|con33| (cons '|Nil| (vector))))
                                (let ((|con34| (cons '|Cons| (vector |con32| |con33|))))
                                  (let ((|con35| (cons '|Node| (vector |c29| |con34|))))
                                    (let ((|con36| (cons '|Empty| (vector))))
                                      (let ((|con37| (cons '|Nil| (vector))))
                                        (let ((|con38| (cons '|Cons| (vector |con36| |con37|))))
                                          (let ((|con39| (cons '|Cons| (vector |con35| |con38|))))
                                            (let ((|con40| (cons '|Cons| (vector |con28| |con39|))))
                                              (let ((|con41| (cons '|Node| (vector |c21| |con40|))))
                                                (let ((|u42| nil))
                                                  (let ((|pair43| (cons |con41| |u42|)))
                                                    (let ((|_code1003| (svref (cdr |countTree#clo1006|) 0)))
                                                      (let ((|Γc1004| (svref (cdr |countTree#clo1006|) 1)))
                                                        (let ((|ρc1005| (cons |pair43| |Γc1004|)))
                                                          (funcall |_code1003| |ρc1005| |k|))))))))))))))))))))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

