;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#f| (car |α|)))
      (let ((|_pR#f| (cdr |α|)))
        (cond
          ((eq (car |_pR#f|) '|None|)
            (let ((|con2| (cons '|None| (vector))))
              (funcall |k| |con2|)))
          ((eq (car |_pR#f|) '|Some|)
            (let ((|p3| (svref (cdr |_pR#f|) 0)))
              (let ((|u4| nil))
                (let ((|pair5| (cons |p3| |u4|)))
                  (let ((|_code| (svref (cdr |_pL#f|) 0)))
                    (let ((|Γc| (svref (cdr |_pL#f|) 1)))
                      (let ((|ρc| (cons |pair5| |Γc|)))
                        (labels ((|k1| (|v0|)
                          (let ((|con7| (cons '|Some| (vector |v0|))))
                            (funcall |k| |con7|))))
                          (funcall |_code| |ρc| #'|k1|))))))))))))))

(defun |listMap| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#f| (car |α|)))
        (let ((|_pR#f| (cdr |α|)))
          (cond
            ((eq (car |_pR#f|) '|Nil|)
              (let ((|con12| (cons '|Nil| (vector))))
                (funcall |k| |con12|)))
            ((eq (car |_pR#f|) '|Cons|)
              (let ((|p13| (svref (cdr |_pR#f|) 0)))
                (let ((|p14| (svref (cdr |_pR#f|) 1)))
                  (let ((|u15| nil))
                    (let ((|pair16| (cons |p13| |u15|)))
                      (let ((|_code| (svref (cdr |_pL#f|) 0)))
                        (let ((|Γc| (svref (cdr |_pL#f|) 1)))
                          (let ((|ρc| (cons |pair16| |Γc|)))
                            (labels ((|k3| (|v2|)
                              (let ((|pair18| (cons |_pL#f| |p14|)))
                                (let ((|ρ| (cons |pair18| |Γ|)))
                                  (labels ((|k5| (|v4|)
                                    (let ((|con20| (cons '|Cons| (vector |v2| |v4|))))
                                      (funcall |k| |con20|))))
                                    (funcall #'|listMap| |ρ| #'|k5|))))))
                              (funcall |_code| |ρc| #'|k3|))))))))))))))))

(defun |fn1001| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (funcall |k| |_pL#x|))))

(defun |fn1002| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|c26| 2))
        (let ((|p27| (+ |c26| |_pL#?x₀|)))
          (funcall |k| |p27|))))))

(defun |fn1006| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam23| (svref (cdr |Γ|) 1)))
        (let ((|c34| (svref (cdr |Γ|) 0)))
          (let ((|pair37| (cons |c34| |α|)))
            (let ((|_code| (svref (cdr |lam23|) 0)))
              (let ((|Γc| (svref (cdr |lam23|) 1)))
                (let ((|ρc| (cons |pair37| |Γc|)))
                  (funcall |_code| |ρc| |k|))))))))))

; entrypoint
(defun |main| (|arg| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|listMap| (cons '|𝐂| (vector #'|listMap| |Γ|))))
      (let ((|Γ| (cons '|𝐄| (vector))))
        (let ((|lam23| (cons '|𝐂| (vector #'|fn1001| |Γ|))))
          (let ((|Γ| (cons '|𝐄| (vector))))
            (let ((|lam28| (cons '|𝐂| (vector #'|fn1002| |Γ|))))
              (let ((|c29| 1))
                (let ((|con30| (cons '|Some| (vector |c29|))))
                  (let ((|pair31| (cons |lam28| |con30|)))
                    (let ((|ρc1005| (cons |pair31| |Γ|)))
                      (labels ((|k7| (|v6|)
                        (let ((|c34| t))
                          (let ((|Γ| (cons '|𝐄| (vector |c34| |lam23|))))
                            (let ((|clos38| (cons '|𝐂| (vector #'|fn1006| |Γ|))))
                              (let ((|c39| 1))
                                (let ((|c40| 2))
                                  (let ((|c41| 3))
                                    (let ((|con42| (cons '|Nil| (vector))))
                                      (let ((|con43| (cons '|Cons| (vector |c41| |con42|))))
                                        (let ((|con44| (cons '|Cons| (vector |c40| |con43|))))
                                          (let ((|con45| (cons '|Cons| (vector |c39| |con44|))))
                                            (let ((|pair46| (cons |clos38| |con45|)))
                                              (let ((|ρc1009| (cons |pair46| |Γ|)))
                                                (labels ((|k9| (|v8|)
                                                  (let ((|p48| (cons |v6| |v8|)))
                                                    (funcall |k| |p48|))))
                                                  (funcall #'|listMap| |ρc1009| #'|k9|))))))))))))))))
                        (funcall #'|fn1000| |ρc1005| #'|k7|)))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

