;; == Runtime ==
(load "runtime.lisp")

;; == Linked Lisp Source ==
(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#f| (car |α|)))
      (let ((|_pR#f| (cdr |α|)))
        (cond
          ((eq (car |_pR#f|) '|None|)
            (let ((|con1| (cons '|None| (vector))))
              (funcall (the function |k|) |con1|)))
          ((eq (car |_pR#f|) '|Some|)
            (let ((|p2| (svref (cdr |_pR#f|) 0)))
              (let ((|u3| nil))
                (let ((|pair4| (cons |p2| |u3|)))
                  (let ((|_code1001| (svref (cdr |_pL#f|) 0)))
                    (let ((|Γc1002| (svref (cdr |_pL#f|) 1)))
                      (let ((|ρc1003| (cons |pair4| |Γc1002|)))
                        (labels ((|k1| (|v0|)
                          (let ((|con6| (cons '|Some| (vector |v0|))))
                            (funcall (the function |k|) |con6|))))
                          (funcall (the function |_code1001|) |ρc1003| #'|k1|))))))))))))))

(defun |listMap| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#f| (car |α|)))
        (let ((|_pR#f| (cdr |α|)))
          (cond
            ((eq (car |_pR#f|) '|Nil|)
              (let ((|con10| (cons '|Nil| (vector))))
                (funcall (the function |k|) |con10|)))
            ((eq (car |_pR#f|) '|Cons|)
              (let ((|p11| (svref (cdr |_pR#f|) 0)))
                (let ((|p12| (svref (cdr |_pR#f|) 1)))
                  (let ((|u13| nil))
                    (let ((|pair14| (cons |p11| |u13|)))
                      (let ((|_code1005| (svref (cdr |_pL#f|) 0)))
                        (let ((|Γc1006| (svref (cdr |_pL#f|) 1)))
                          (let ((|ρc1007| (cons |pair14| |Γc1006|)))
                            (labels ((|k3| (|v2|)
                              (let ((|pair16| (cons |_pL#f| |p12|)))
                                (let ((|ρ1004| (cons |pair16| |Γ|)))
                                  (labels ((|k5| (|v4|)
                                    (let ((|con18| (cons '|Cons| (vector |v2| |v4|))))
                                      (funcall (the function |k|) |con18|))))
                                    (funcall #'|listMap| |ρ1004| #'|k5|))))))
                              (funcall (the function |_code1005|) |ρc1007| #'|k3|))))))))))))))))

(defun |fn1008| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (funcall (the function |k|) |_pL#x|))))

(defun |fn1009| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#?x₀| (car |α|)))
      (let ((|c24| 2))
        (let ((|p25| (%int+ |c24| |_pL#?x₀|)))
          (funcall (the function |k|) |p25|))))))

(defun |fn1013| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam21| (svref (cdr |Γ|) 1)))
        (let ((|c32| (svref (cdr |Γ|) 0)))
          (let ((|_pL#arg34| (car |α|)))
            (let ((|pair37| (cons |c32| |_pL#arg34|)))
              (let ((|_code1014| (svref (cdr |lam21|) 0)))
                (let ((|Γc1015| (svref (cdr |lam21|) 1)))
                  (let ((|ρc1016| (cons |pair37| |Γc1015|)))
                    (funcall (the function |_code1014|) |ρc1016| |k|)))))))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|lam21| (cons '|𝐂| (vector #'|fn1008| |Γ|))))
      (let ((|Γ| (cons '|𝐄| (vector))))
        (let ((|lam26| (cons '|𝐂| (vector #'|fn1009| |Γ|))))
          (let ((|c27| 1))
            (let ((|con28| (cons '|Some| (vector |c27|))))
              (let ((|pair29| (cons |lam26| |con28|)))
                (let ((|ρc1012| (cons |pair29| |Γ|)))
                  (labels ((|k7| (|v6|)
                    (let ((|c32| t))
                      (let ((|Γ| (cons '|𝐄| (vector |c32| |lam21|))))
                        (let ((|clos38| (cons '|𝐂| (vector #'|fn1013| |Γ|))))
                          (let ((|c39| 1))
                            (let ((|c40| 2))
                              (let ((|c41| 3))
                                (let ((|con42| (cons '|Nil| (vector))))
                                  (let ((|con43| (cons '|Cons| (vector |c41| |con42|))))
                                    (let ((|con44| (cons '|Cons| (vector |c40| |con43|))))
                                      (let ((|con45| (cons '|Cons| (vector |c39| |con44|))))
                                        (let ((|pair46| (cons |clos38| |con45|)))
                                          (let ((|ρc1019| (cons |pair46| |Γ|)))
                                            (labels ((|k9| (|v8|)
                                              (let ((|p48| (cons |v6| |v8|)))
                                                (funcall (the function |k|) |p48|))))
                                              (funcall #'|listMap| |ρc1019| #'|k9|))))))))))))))))
                    (funcall #'|fn1000| |ρc1012| #'|k7|)))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

