;; == Runtime ==
(load "runtime.lisp")

;; == Linked Lisp Source ==
(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1003| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1004| (car |payload|)))
    (let ((|_pL#f| (car |α1004|)))
      (let ((|_pR#f| (cdr |α1004|)))
        (cond
          ((eq (car |_pR#f|) '|None|)
            (let ((|con1| (cons '|None| (vector))))
              (funcall (the function |k|) |con1|)))
          ((eq (car |_pR#f|) '|Some|)
            (let ((|p2| (svref (cdr |_pR#f|) 0)))
              (let ((|u3| nil))
                (let ((|pair4| (cons |p2| |u3|)))
                  (let ((|_code1006| (svref (cdr |_pL#f|) 0)))
                    (let ((|Γc1007| (svref (cdr |_pL#f|) 1)))
                      (let ((|ρc1008| (cons |pair4| |Γc1007|)))
                        (labels ((|k1| (|v0|)
                          (let ((|con6| (cons '|Some| (vector |v0|))))
                            (funcall (the function |k|) |con6|))))
                          (funcall (the function |_code1006|) |ρc1008| #'|k1|))))))))))))))

(defun |listMap| (|payload1009| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1009|))
  (let ((|α1010| (car |payload1009|)))
    (let ((|Γ1011| (cdr |payload1009|)))
      (let ((|_pL#f| (car |α1010|)))
        (let ((|_pR#f| (cdr |α1010|)))
          (cond
            ((eq (car |_pR#f|) '|Nil|)
              (let ((|con10| (cons '|Nil| (vector))))
                (funcall (the function |k|) |con10|)))
            ((eq (car |_pR#f|) '|Cons|)
              (let ((|p11| (svref (cdr |_pR#f|) 0)))
                (let ((|p12| (svref (cdr |_pR#f|) 1)))
                  (let ((|u13| nil))
                    (let ((|pair14| (cons |p11| |u13|)))
                      (let ((|_code1013| (svref (cdr |_pL#f|) 0)))
                        (let ((|Γc1014| (svref (cdr |_pL#f|) 1)))
                          (let ((|ρc1015| (cons |pair14| |Γc1014|)))
                            (labels ((|k3| (|v2|)
                              (let ((|pair16| (cons |_pL#f| |p12|)))
                                (let ((|ρ1012| (cons |pair16| |Γ1011|)))
                                  (labels ((|k5| (|v4|)
                                    (let ((|con18| (cons '|Cons| (vector |v2| |v4|))))
                                      (funcall (the function |k|) |con18|))))
                                    (funcall #'|listMap| |ρ1012| #'|k5|))))))
                              (funcall (the function |_code1013|) |ρc1015| #'|k3|))))))))))))))))

(defun |fn1016| (|payload1017| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1017|))
  (let ((|α1018| (car |payload1017|)))
    (let ((|_pL#x| (car |α1018|)))
      (funcall (the function |k|) |_pL#x|))))

(defun |fn1020| (|payload1021| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1021|))
  (let ((|α1022| (car |payload1021|)))
    (let ((|_pL#?x₀| (car |α1022|)))
      (let ((|c24| 2))
        (let ((|p25| (%int+ |c24| |_pL#?x₀|)))
          (funcall (the function |k|) |p25|))))))

(defun |fn1027| (|payload1028| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1028|))
  (let ((|α1029| (car |payload1028|)))
    (let ((|Γ1030| (cdr |payload1028|)))
      (let ((|lam21| (svref (cdr |Γ1030|) 1)))
        (let ((|c32| (svref (cdr |Γ1030|) 0)))
          (let ((|_pL#arg34| (car |α1029|)))
            (let ((|pair37| (cons |c32| |_pL#arg34|)))
              (let ((|_code1031| (svref (cdr |lam21|) 0)))
                (let ((|Γc1032| (svref (cdr |lam21|) 1)))
                  (let ((|ρc1033| (cons |pair37| |Γc1032|)))
                    (funcall (the function |_code1031|) |ρc1033| |k|)))))))))))

; entrypoint
(defun |main| (|payload1000| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1000|))
  (let ((|Γ1042| (cons '|𝐄| (vector))))
    (let ((|Γ1041| (cons '|𝐄| (vector))))
      (let ((|Γ1039| (cons '|𝐄| (vector))))
        (let ((|lam21| (cons '|𝐂| (vector #'|fn1016| |Γ1039|))))
          (let ((|Γ1038| (cons '|𝐄| (vector))))
            (let ((|lam26| (cons '|𝐂| (vector #'|fn1020| |Γ1038|))))
              (let ((|c27| 1))
                (let ((|con28| (cons '|Some| (vector |c27|))))
                  (let ((|pair29| (cons |lam26| |con28|)))
                    (let ((|ρc1026| (cons |pair29| |Γ1042|)))
                      (labels ((|k7| (|v6|)
                        (let ((|c32| t))
                          (let ((|Γ1037| (cons '|𝐄| (vector |c32| |lam21|))))
                            (let ((|clos38| (cons '|𝐂| (vector #'|fn1027| |Γ1037|))))
                              (let ((|c39| 1))
                                (let ((|c40| 2))
                                  (let ((|c41| 3))
                                    (let ((|con42| (cons '|Nil| (vector))))
                                      (let ((|con43| (cons '|Cons| (vector |c41| |con42|))))
                                        (let ((|con44| (cons '|Cons| (vector |c40| |con43|))))
                                          (let ((|con45| (cons '|Cons| (vector |c39| |con44|))))
                                            (let ((|pair46| (cons |clos38| |con45|)))
                                              (let ((|ρc1036| (cons |pair46| |Γ1041|)))
                                                (labels ((|k9| (|v8|)
                                                  (let ((|p48| (cons |v6| |v8|)))
                                                    (funcall (the function |k|) |p48|))))
                                                  (funcall #'|listMap| |ρc1036| #'|k9|))))))))))))))))
                        (funcall #'|fn1003| |ρc1026| #'|k7|)))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

