;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (let ((|_pR#x| (cdr |α|)))
        (let ((|p1| (= |_pL#x| |_pR#x|)))
          (funcall |k| |p1|))))))

(defun |f5| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#d_Eq_0| (svref (cdr |Γ|) 0)))
        (let ((|_pL#?x₀| (car |α|)))
          (let ((|_pR#?x₀| (cdr |α|)))
            (cond
              ((eq (car |_pL#?x₀|) '|Nil|)
                (cond
                  ((eq (car |_pR#?x₀|) '|Nil|)
                    (let ((|c8| t))
                      (funcall |k| |c8|)))
                  (t
                    (let ((|c9| nil))
                      (funcall |k| |c9|)))))
              ((eq (car |_pL#?x₀|) '|Cons|)
                (cond
                  ((eq (car |_pR#?x₀|) '|Cons|)
                    (let ((|p10| (svref (cdr |_pL#?x₀|) 0)))
                      (let ((|p11| (svref (cdr |_pL#?x₀|) 1)))
                        (let ((|p12| (svref (cdr |_pR#?x₀|) 0)))
                          (let ((|p13| (svref (cdr |_pR#?x₀|) 1)))
                            (let ((|p14| (svref (cdr |_pL#d_Eq_0|) 0)))
                              (let ((|pair15| (cons |p10| |p12|)))
                                (let ((|_code| (svref (cdr |p14|) 0)))
                                  (let ((|Γc| (svref (cdr |p14|) 1)))
                                    (let ((|ρc| (cons |pair15| |Γc|)))
                                      (labels ((|k1| (|v0|)
                                        (if |v0|
                                          (let ((|pair17| (cons |p11| |p13|)))
                                            (let ((|ρ| (cons |pair17| |Γ|)))
                                              (funcall #'|f5| |ρ| |k|)))
                                          (let ((|c19| nil))
                                            (funcall |k| |c19|)))))
                                        (funcall |_code| |ρc| #'|k1|))))))))))))
                  (t
                    (let ((|c20| nil))
                      (funcall |k| |c20|)))))
              (t
                (let ((|c21| nil))
                  (funcall |k| |c21|))))))))))

(defun |fn1001| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|_pL#d_Eq_0| (car |α|)))
      (let ((|Γ| (cons '|𝐄| (vector |_pL#d_Eq_0|))))
        (let ((|f5| (cons '|𝐂| (vector #'|f5| |Γ|))))
          (funcall |k| |f5|))))))

(defun |fn1002| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam23| (svref (cdr |Γ|) 0)))
        (let ((|_pL#d_Eq_0| (car |α|)))
          (let ((|u25| nil))
            (let ((|pair26| (cons |_pL#d_Eq_0| |u25|)))
              (let ((|_code| (svref (cdr |lam23|) 0)))
                (let ((|Γc| (svref (cdr |lam23|) 1)))
                  (let ((|ρc| (cons |pair26| |Γc|)))
                    (labels ((|k3| (|v2|)
                      (let ((|con28| (cons '|Eq| (vector |v2|))))
                        (funcall |k| |con28|))))
                      (funcall |_code| |ρc| #'|k3|))))))))))))

; entrypoint
(defun |main| (|arg| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|lam2| (cons '|𝐂| (vector #'|fn1000| |Γ|))))
      (let ((|con3| (cons '|Eq| (vector |lam2|))))
        (let ((|Γ| (cons '|𝐄| (vector))))
          (let ((|lam23| (cons '|𝐂| (vector #'|fn1001| |Γ|))))
            (let ((|Γ| (cons '|𝐄| (vector |lam23|))))
              (let ((|u30| nil))
                (let ((|pair31| (cons |con3| |u30|)))
                  (let ((|ρc1005| (cons |pair31| |Γ|)))
                    (labels ((|k5| (|v4|)
                      (let ((|p33| (svref (cdr |v4|) 0)))
                        (let ((|c34| 1))
                          (let ((|c35| 2))
                            (let ((|con36| (cons '|Nil| (vector))))
                              (let ((|con37| (cons '|Cons| (vector |c35| |con36|))))
                                (let ((|con38| (cons '|Cons| (vector |c34| |con37|))))
                                  (let ((|c39| 1))
                                    (let ((|c40| 2))
                                      (let ((|c41| 3))
                                        (let ((|con42| (cons '|Nil| (vector))))
                                          (let ((|con43| (cons '|Cons| (vector |c41| |con42|))))
                                            (let ((|con44| (cons '|Cons| (vector |c40| |con43|))))
                                              (let ((|con45| (cons '|Cons| (vector |c39| |con44|))))
                                                (let ((|pair46| (cons |con38| |con45|)))
                                                  (let ((|_code1006| (svref (cdr |p33|) 0)))
                                                    (let ((|Γc1007| (svref (cdr |p33|) 1)))
                                                      (let ((|ρc1008| (cons |pair46| |Γc1007|)))
                                                        (labels ((|k7| (|v6|)
                                                          (let ((|p48| (svref (cdr |v4|) 0)))
                                                            (let ((|c49| 1))
                                                              (let ((|c50| 2))
                                                                (let ((|c51| 3))
                                                                  (let ((|con52| (cons '|Nil| (vector))))
                                                                    (let ((|con53| (cons '|Cons| (vector |c51| |con52|))))
                                                                      (let ((|con54| (cons '|Cons| (vector |c50| |con53|))))
                                                                        (let ((|con55| (cons '|Cons| (vector |c49| |con54|))))
                                                                          (let ((|c56| 1))
                                                                            (let ((|c57| 2))
                                                                              (let ((|c58| 3))
                                                                                (let ((|con59| (cons '|Nil| (vector))))
                                                                                  (let ((|con60| (cons '|Cons| (vector |c58| |con59|))))
                                                                                    (let ((|con61| (cons '|Cons| (vector |c57| |con60|))))
                                                                                      (let ((|con62| (cons '|Cons| (vector |c56| |con61|))))
                                                                                        (let ((|pair63| (cons |con55| |con62|)))
                                                                                          (let ((|_code1009| (svref (cdr |p48|) 0)))
                                                                                            (let ((|Γc1010| (svref (cdr |p48|) 1)))
                                                                                              (let ((|ρc1011| (cons |pair63| |Γc1010|)))
                                                                                                (labels ((|k9| (|v8|)
                                                                                                  (let ((|p65| (cons |v6| |v8|)))
                                                                                                    (funcall |k| |p65|))))
                                                                                                  (funcall |_code1009| |ρc1011| #'|k9|)))))))))))))))))))))))
                                                          (funcall |_code1006| |ρc1008| #'|k7|)))))))))))))))))))))
                      (funcall #'|fn1002| |ρc1005| #'|k5|))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

