;; == Runtime ==
(load "runtime.lisp")

;; == Linked Lisp Source ==
(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1003| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1004| (car |payload|)))
  (let ((|_pL#x| (car |α1004|)))
  (let ((|_pR#x| (cdr |α1004|)))
  (let ((|p1| (%int= |_pL#x| |_pR#x|)))
  (funcall (the function |k|) |p1|))))))

(defun |f5| (|payload1009| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1009|))
  (let ((|α1010| (car |payload1009|)))
  (let ((|Γ1011| (cdr |payload1009|)))
  (let ((|_pL#d_Eq_0| (svref (cdr |Γ1011|) 0)))
  (let ((|_pL#?x₀| (car |α1010|)))
  (let ((|_pR#?x₀| (cdr |α1010|)))
  (cond
    ((eq (car |_pL#?x₀|) '|Nil|)
      (cond
      ((eq (car |_pR#?x₀|) '|Nil|)
        (let ((|c7| t))
        (funcall (the function |k|) |c7|)))
      (t
        (let ((|c8| nil))
          (funcall (the function |k|) |c8|)))))
    ((eq (car |_pL#?x₀|) '|Cons|)
      (cond
      ((eq (car |_pR#?x₀|) '|Cons|)
        (let ((|p9| (svref (cdr |_pL#?x₀|) 0)))
        (let ((|p10| (svref (cdr |_pL#?x₀|) 1)))
        (let ((|p11| (svref (cdr |_pR#?x₀|) 0)))
        (let ((|p12| (svref (cdr |_pR#?x₀|) 1)))
        (let ((|p13| (svref (cdr |_pL#d_Eq_0|) 0)))
        (let ((|pair14| (cons |p9| |p11|)))
        (let ((|_code1013| (svref (cdr |p13|) 0)))
        (let ((|Γc1014| (svref (cdr |p13|) 1)))
        (let ((|ρc1015| (cons |pair14| |Γc1014|)))
        (labels
          ((|k1| (|v0|)
            (if |v0|
            (let ((|pair16| (cons |p10| |p12|)))
              (let ((|ρ1012| (cons |pair16| |Γ1011|)))
              (funcall #'|f5| |ρ1012| |k|)))
            (let ((|c18| nil))
              (funcall (the function |k|) |c18|)))))
          (funcall (the function |_code1013|) |ρc1015| #'|k1|))))))))))))
      (t
        (let ((|c19| nil))
          (funcall (the function |k|) |c19|)))))
    (t
      (let ((|c20| nil))
        (funcall (the function |k|) |c20|))))))))))

(defun |fn1006| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1007| (car |payload|)))
  (let ((|_pL#d_Eq_0| (car |α1007|)))
  (let ((|Γ1017| (cons '|𝐄| (vector |_pL#d_Eq_0|))))
  (let ((|f5#clo1016| (cons '|𝐂| (vector #'|f5| |Γ1017|))))
  (funcall (the function |k|) |f5#clo1016|))))))

(defun |fn1021| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1022| (car |payload|)))
  (let ((|Γ1023| (cdr |payload|)))
  (let ((|_pL#d_Eq_0| (svref (cdr |Γ1023|) 0)))
  (let ((|_pL#?x₀| (car |α1022|)))
  (let ((|_pR#?x₀| (cdr |α1022|)))
  (cond
    ((eq (car |_pL#?x₀|) '|None|)
      (cond
      ((eq (car |_pR#?x₀|) '|None|)
        (let ((|c25| t))
        (funcall (the function |k|) |c25|)))
      (t
        (let ((|c26| nil))
          (funcall (the function |k|) |c26|)))))
    ((eq (car |_pL#?x₀|) '|Some|)
      (cond
      ((eq (car |_pR#?x₀|) '|Some|)
        (let ((|p27| (svref (cdr |_pL#?x₀|) 0)))
        (let ((|p28| (svref (cdr |_pR#?x₀|) 0)))
        (let ((|p29| (svref (cdr |_pL#d_Eq_0|) 0)))
        (let ((|pair30| (cons |p27| |p28|)))
        (let ((|_code1024| (svref (cdr |p29|) 0)))
        (let ((|Γc1025| (svref (cdr |p29|) 1)))
        (let ((|ρc1026| (cons |pair30| |Γc1025|)))
        (funcall (the function |_code1024|) |ρc1026| |k|)))))))))
      (t
        (let ((|c32| nil))
          (funcall (the function |k|) |c32|)))))
    (t
      (let ((|c33| nil))
        (funcall (the function |k|) |c33|))))))))))

(defun |fn1018| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1019| (car |payload|)))
  (let ((|_pL#d_Eq_0| (car |α1019|)))
  (let ((|Γ1027| (cons '|𝐄| (vector |_pL#d_Eq_0|))))
  (let ((|lam34| (cons '|𝐂| (vector #'|fn1021| |Γ1027|))))
  (let ((|con35| (cons '|Eq| (vector |lam34|))))
  (funcall (the function |k|) |con35|)))))))

(defun |fn1028| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α1029| (car |payload|)))
  (let ((|Γ1030| (cdr |payload|)))
  (let ((|lam22| (svref (cdr |Γ1030|) 0)))
  (let ((|_pL#d_Eq_0| (car |α1029|)))
  (let ((|u38| nil))
  (let ((|pair39| (cons |_pL#d_Eq_0| |u38|)))
  (let ((|_code1031| (svref (cdr |lam22|) 0)))
  (let ((|Γc1032| (svref (cdr |lam22|) 1)))
  (let ((|ρc1033| (cons |pair39| |Γc1032|)))
  (labels
    ((|k3| (|v2|)
      (let ((|con41| (cons '|Eq| (vector |v2|))))
      (funcall (the function |k|) |con41|))))
    (funcall (the function |_code1031|) |ρc1033| #'|k3|))))))))))))

; entrypoint
(defun |main| (|payload1000| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload1000|))
  (let ((|Γ1058| (cons '|𝐄| (vector))))
  (let ((|lam2| (cons '|𝐂| (vector #'|fn1003| |Γ1058|))))
  (let ((|con3| (cons '|Eq| (vector |lam2|))))
  (let ((|Γ1057| (cons '|𝐄| (vector))))
  (let ((|lam22| (cons '|𝐂| (vector #'|fn1006| |Γ1057|))))
  (let ((|Γ1056| (cons '|𝐄| (vector))))
  (let ((|Γ1055| (cons '|𝐄| (vector |lam22|))))
  (let ((|u43| nil))
  (let ((|pair44| (cons |con3| |u43|)))
  (let ((|ρc1054| (cons |pair44| |Γ1055|)))
  (labels
    ((|k5| (|v4|)
      (let ((|u46| nil))
      (let ((|pair47| (cons |con3| |u46|)))
      (let ((|ρc1051| (cons |pair47| |Γ1056|)))
      (labels
        ((|k7| (|v6|)
          (let ((|p49| (svref (cdr |v4|) 0)))
          (let ((|c50| 1))
          (let ((|c51| 2))
          (let ((|con52| (cons '|Nil| (vector))))
          (let ((|con53| (cons '|Cons| (vector |c51| |con52|))))
          (let ((|con54| (cons '|Cons| (vector |c50| |con53|))))
          (let ((|c55| 1))
          (let ((|c56| 2))
          (let ((|c57| 3))
          (let ((|con58| (cons '|Nil| (vector))))
          (let ((|con59| (cons '|Cons| (vector |c57| |con58|))))
          (let ((|con60| (cons '|Cons| (vector |c56| |con59|))))
          (let ((|con61| (cons '|Cons| (vector |c55| |con60|))))
          (let ((|pair62| (cons |con54| |con61|)))
          (let ((|_code1046| (svref (cdr |p49|) 0)))
          (let ((|Γc1047| (svref (cdr |p49|) 1)))
          (let ((|ρc1048| (cons |pair62| |Γc1047|)))
          (labels
            ((|k9| (|v8|)
              (let ((|p64| (svref (cdr |v4|) 0)))
              (let ((|c65| 1))
              (let ((|c66| 2))
              (let ((|c67| 3))
              (let ((|con68| (cons '|Nil| (vector))))
              (let ((|con69| (cons '|Cons| (vector |c67| |con68|))))
              (let ((|con70| (cons '|Cons| (vector |c66| |con69|))))
              (let ((|con71| (cons '|Cons| (vector |c65| |con70|))))
              (let ((|c72| 1))
              (let ((|c73| 2))
              (let ((|c74| 3))
              (let ((|con75| (cons '|Nil| (vector))))
              (let ((|con76| (cons '|Cons| (vector |c74| |con75|))))
              (let ((|con77| (cons '|Cons| (vector |c73| |con76|))))
              (let ((|con78| (cons '|Cons| (vector |c72| |con77|))))
              (let ((|pair79| (cons |con71| |con78|)))
              (let ((|_code1043| (svref (cdr |p64|) 0)))
              (let ((|Γc1044| (svref (cdr |p64|) 1)))
              (let ((|ρc1045| (cons |pair79| |Γc1044|)))
              (labels
                ((|k11| (|v10|)
                  (let ((|p81| (svref (cdr |v6|) 0)))
                  (let ((|c82| 1))
                  (let ((|con83| (cons '|Some| (vector |c82|))))
                  (let ((|c84| 2))
                  (let ((|con85| (cons '|Some| (vector |c84|))))
                  (let ((|pair86| (cons |con83| |con85|)))
                  (let ((|_code1040| (svref (cdr |p81|) 0)))
                  (let ((|Γc1041| (svref (cdr |p81|) 1)))
                  (let ((|ρc1042| (cons |pair86| |Γc1041|)))
                  (labels
                    ((|k13| (|v12|)
                      (let ((|p88| (svref (cdr |v6|) 0)))
                      (let ((|c89| 1))
                      (let ((|con90| (cons '|Some| (vector |c89|))))
                      (let ((|c91| 1))
                      (let ((|con92| (cons '|Some| (vector |c91|))))
                      (let ((|pair93| (cons |con90| |con92|)))
                      (let ((|_code1037| (svref (cdr |p88|) 0)))
                      (let ((|Γc1038| (svref (cdr |p88|) 1)))
                      (let ((|ρc1039| (cons |pair93| |Γc1038|)))
                      (labels
                        ((|k15| (|v14|)
                          (let ((|p95| (svref (cdr |v6|) 0)))
                          (let ((|c96| 1))
                          (let ((|con97| (cons '|Some| (vector |c96|))))
                          (let ((|con98| (cons '|None| (vector))))
                          (let ((|pair99| (cons |con97| |con98|)))
                          (let ((|_code1034| (svref (cdr |p95|) 0)))
                          (let ((|Γc1035| (svref (cdr |p95|) 1)))
                          (let ((|ρc1036| (cons |pair99| |Γc1035|)))
                          (labels
                            ((|k17| (|v16|)
                              (let ((|c101| 2))
                              (let ((|con102| (cons '|Some| (vector |c101|))))
                              (let ((|con103| (cons '|None| (vector))))
                              (let ((|p104| (cons |con102| |con103|)))
                              (let ((|p105| (cons |v16| |p104|)))
                              (let ((|p106| (cons |v14| |p105|)))
                              (let ((|p107| (cons |v12| |p106|)))
                              (let ((|p108| (cons |v10| |p107|)))
                              (let ((|p109| (cons |v8| |p108|)))
                              (funcall (the function |k|) |p109|))))))))))))
                            (funcall (the function |_code1034|) |ρc1036| #'|k17|))))))))))))
                        (funcall (the function |_code1037|) |ρc1039| #'|k15|)))))))))))))
                    (funcall (the function |_code1040|) |ρc1042| #'|k13|)))))))))))))
                (funcall (the function |_code1043|) |ρc1045| #'|k11|)))))))))))))))))))))))
            (funcall (the function |_code1046|) |ρc1048| #'|k9|)))))))))))))))))))))
        (funcall #'|fn1018| |ρc1051| #'|k7|)))))))
    (funcall #'|fn1028| |ρc1054| #'|k5|)))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

