;; == Runtime ==
(load "runtime.lisp")

;; == Linked Lisp Source ==
(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (let ((|con1| (cons '|Some| (vector |_pL#x|))))
        (funcall (the function |k|) |con1|)))))

(defun |fn1001| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (let ((|_pR#x| (cdr |α|)))
        (cond
          ((eq (car |_pL#x|) '|None|)
            (let ((|con4| (cons '|None| (vector))))
              (funcall (the function |k|) |con4|)))
          ((eq (car |_pL#x|) '|Some|)
            (let ((|p5| (svref (cdr |_pL#x|) 0)))
              (let ((|u6| nil))
                (let ((|pair7| (cons |p5| |u6|)))
                  (let ((|_code1002| (svref (cdr |_pR#x|) 0)))
                    (let ((|Γc1003| (svref (cdr |_pR#x|) 1)))
                      (let ((|ρc1004| (cons |pair7| |Γc1003|)))
                        (funcall (the function |_code1002|) |ρc1004| |k|)))))))))))))

(defun |fn1007| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam2| (svref (cdr |Γ|) 2)))
        (let ((|_pL#y| (svref (cdr |Γ|) 1)))
          (let ((|_pL#x| (svref (cdr |Γ|) 0)))
            (let ((|_pL#z| (car |α|)))
              (let ((|p29| (%int+ |_pL#x| |_pL#y|)))
                (let ((|p30| (%int+ |p29| |_pL#z|)))
                  (let ((|u31| nil))
                    (let ((|pair32| (cons |p30| |u31|)))
                      (let ((|_code1008| (svref (cdr |lam2|) 0)))
                        (let ((|Γc1009| (svref (cdr |lam2|) 1)))
                          (let ((|ρc1010| (cons |pair32| |Γc1009|)))
                            (funcall (the function |_code1008|) |ρc1010| |k|)))))))))))))))

(defun |fn1006| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam9| (svref (cdr |Γ|) 2)))
        (let ((|lam2| (svref (cdr |Γ|) 1)))
          (let ((|_pL#x| (svref (cdr |Γ|) 0)))
            (let ((|_pL#y| (car |α|)))
              (let ((|c23| 30))
                (let ((|u24| nil))
                  (let ((|pair25| (cons |c23| |u24|)))
                    (let ((|_code1014| (svref (cdr |lam2|) 0)))
                      (let ((|Γc1015| (svref (cdr |lam2|) 1)))
                        (let ((|ρc1016| (cons |pair25| |Γc1015|)))
                          (labels ((|k1| (|v0|)
                            (let ((|Γ| (cons '|𝐄| (vector |_pL#x| |_pL#y| |lam2|))))
                              (let ((|lam34| (cons '|𝐂| (vector #'|fn1007| |Γ|))))
                                (let ((|pair35| (cons |v0| |lam34|)))
                                  (let ((|_code1011| (svref (cdr |lam9|) 0)))
                                    (let ((|Γc1012| (svref (cdr |lam9|) 1)))
                                      (let ((|ρc1013| (cons |pair35| |Γc1012|)))
                                        (funcall (the function |_code1011|) |ρc1013| |k|)))))))))
                            (funcall (the function |_code1014|) |ρc1016| #'|k1|)))))))))))))))

(defun |fn1005| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam9| (svref (cdr |Γ|) 1)))
        (let ((|lam2| (svref (cdr |Γ|) 0)))
          (let ((|_pL#x| (car |α|)))
            (let ((|con19| (cons '|None| (vector))))
              (let ((|Γ| (cons '|𝐄| (vector |_pL#x| |lam2| |lam9|))))
                (let ((|lam37| (cons '|𝐂| (vector #'|fn1006| |Γ|))))
                  (let ((|pair38| (cons |con19| |lam37|)))
                    (let ((|_code1017| (svref (cdr |lam9|) 0)))
                      (let ((|Γc1018| (svref (cdr |lam9|) 1)))
                        (let ((|ρc1019| (cons |pair38| |Γc1018|)))
                          (funcall (the function |_code1017|) |ρc1019| |k|))))))))))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|lam2| (cons '|𝐂| (vector #'|fn1000| |Γ|))))
      (let ((|Γ| (cons '|𝐄| (vector))))
        (let ((|lam9| (cons '|𝐂| (vector #'|fn1001| |Γ|))))
          (let ((|c13| 20))
            (let ((|u14| nil))
              (let ((|pair15| (cons |c13| |u14|)))
                (let ((|ρc1025| (cons |pair15| |Γ|)))
                  (labels ((|k3| (|v2|)
                    (let ((|Γ| (cons '|𝐄| (vector |lam2| |lam9|))))
                      (let ((|lam40| (cons '|𝐂| (vector #'|fn1005| |Γ|))))
                        (let ((|pair41| (cons |v2| |lam40|)))
                          (let ((|_code1020| (svref (cdr |lam9|) 0)))
                            (let ((|Γc1021| (svref (cdr |lam9|) 1)))
                              (let ((|ρc1022| (cons |pair41| |Γc1021|)))
                                (funcall (the function |_code1020|) |ρc1022| |k|)))))))))
                    (funcall #'|fn1000| |ρc1025| #'|k3|)))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

