;; == external FFI ==

(load "ffi.lisp")

;; == Common Lisp ==

; hoisted functions

(defun |fn1000| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#x| (car |α|)))
      (let ((|_pR#x| (cdr |α|)))
        (let ((|p1| (%int= |_pL#x| |_pR#x|)))
          (funcall (the function |k|) |p1|))))))

(defun |f5| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#d_Eq_0| (svref (cdr |Γ|) 0)))
        (let ((|_pL#?x₀| (car |α|)))
          (let ((|_pR#?x₀| (cdr |α|)))
            (cond
              ((eq (car |_pL#?x₀|) '|Nil|)
                (cond
                  ((eq (car |_pR#?x₀|) '|Nil|)
                    (let ((|c7| t))
                      (funcall (the function |k|) |c7|)))
                  (t
                    (let ((|c8| nil))
                      (funcall (the function |k|) |c8|)))))
              ((eq (car |_pL#?x₀|) '|Cons|)
                (cond
                  ((eq (car |_pR#?x₀|) '|Cons|)
                    (let ((|p9| (svref (cdr |_pL#?x₀|) 0)))
                      (let ((|p10| (svref (cdr |_pL#?x₀|) 1)))
                        (let ((|p11| (svref (cdr |_pR#?x₀|) 0)))
                          (let ((|p12| (svref (cdr |_pR#?x₀|) 1)))
                            (let ((|p13| (svref (cdr |_pL#d_Eq_0|) 0)))
                              (let ((|pair14| (cons |p9| |p11|)))
                                (let ((|_code1003| (svref (cdr |p13|) 0)))
                                  (let ((|Γc1004| (svref (cdr |p13|) 1)))
                                    (let ((|ρc1005| (cons |pair14| |Γc1004|)))
                                      (labels ((|k1| (|v0|)
                                        (if |v0|
                                          (let ((|pair16| (cons |p10| |p12|)))
                                            (let ((|ρ1002| (cons |pair16| |Γ|)))
                                              (funcall #'|f5| |ρ1002| |k|)))
                                          (let ((|c18| nil))
                                            (funcall (the function |k|) |c18|)))))
                                        (funcall (the function |_code1003|) |ρc1005| #'|k1|))))))))))))
                  (t
                    (let ((|c19| nil))
                      (funcall (the function |k|) |c19|)))))
              (t
                (let ((|c20| nil))
                  (funcall (the function |k|) |c20|))))))))))

(defun |fn1001| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#d_Eq_0| (car |α|)))
      (let ((|Γ| (cons '|𝐄| (vector |_pL#d_Eq_0|))))
        (let ((|f5#clo1006| (cons '|𝐂| (vector #'|f5| |Γ|))))
          (funcall (the function |k|) |f5#clo1006|))))))

(defun |fn1008| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|_pL#d_Eq_0| (svref (cdr |Γ|) 0)))
        (let ((|_pL#?x₀| (car |α|)))
          (let ((|_pR#?x₀| (cdr |α|)))
            (cond
              ((eq (car |_pL#?x₀|) '|None|)
                (cond
                  ((eq (car |_pR#?x₀|) '|None|)
                    (let ((|c25| t))
                      (funcall (the function |k|) |c25|)))
                  (t
                    (let ((|c26| nil))
                      (funcall (the function |k|) |c26|)))))
              ((eq (car |_pL#?x₀|) '|Some|)
                (cond
                  ((eq (car |_pR#?x₀|) '|Some|)
                    (let ((|p27| (svref (cdr |_pL#?x₀|) 0)))
                      (let ((|p28| (svref (cdr |_pR#?x₀|) 0)))
                        (let ((|p29| (svref (cdr |_pL#d_Eq_0|) 0)))
                          (let ((|pair30| (cons |p27| |p28|)))
                            (let ((|_code1009| (svref (cdr |p29|) 0)))
                              (let ((|Γc1010| (svref (cdr |p29|) 1)))
                                (let ((|ρc1011| (cons |pair30| |Γc1010|)))
                                  (funcall (the function |_code1009|) |ρc1011| |k|)))))))))
                  (t
                    (let ((|c32| nil))
                      (funcall (the function |k|) |c32|)))))
              (t
                (let ((|c33| nil))
                  (funcall (the function |k|) |c33|))))))))))

(defun |fn1007| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|_pL#d_Eq_0| (car |α|)))
      (let ((|Γ| (cons '|𝐄| (vector |_pL#d_Eq_0|))))
        (let ((|lam34| (cons '|𝐂| (vector #'|fn1008| |Γ|))))
          (let ((|con35| (cons '|Eq| (vector |lam34|))))
            (funcall (the function |k|) |con35|)))))))

(defun |fn1012| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|α| (car |payload|)))
    (let ((|Γ| (cdr |payload|)))
      (let ((|lam22| (svref (cdr |Γ|) 0)))
        (let ((|_pL#d_Eq_0| (car |α|)))
          (let ((|u38| nil))
            (let ((|pair39| (cons |_pL#d_Eq_0| |u38|)))
              (let ((|_code1013| (svref (cdr |lam22|) 0)))
                (let ((|Γc1014| (svref (cdr |lam22|) 1)))
                  (let ((|ρc1015| (cons |pair39| |Γc1014|)))
                    (labels ((|k3| (|v2|)
                      (let ((|con41| (cons '|Eq| (vector |v2|))))
                        (funcall (the function |k|) |con41|))))
                      (funcall (the function |_code1013|) |ρc1015| #'|k3|))))))))))))

; entrypoint
(defun |main| (|payload| |k|)
  (declare (optimize (speed 3) (safety 0) (debug 0)) (ignorable |payload|))
  (let ((|Γ| (cons '|𝐄| (vector))))
    (let ((|lam2| (cons '|𝐂| (vector #'|fn1000| |Γ|))))
      (let ((|con3| (cons '|Eq| (vector |lam2|))))
        (let ((|Γ| (cons '|𝐄| (vector))))
          (let ((|lam22| (cons '|𝐂| (vector #'|fn1001| |Γ|))))
            (let ((|Γ| (cons '|𝐄| (vector |lam22|))))
              (let ((|u43| nil))
                (let ((|pair44| (cons |con3| |u43|)))
                  (let ((|ρc1036| (cons |pair44| |Γ|)))
                    (labels ((|k5| (|v4|)
                      (let ((|u46| nil))
                        (let ((|pair47| (cons |con3| |u46|)))
                          (let ((|ρc1033| (cons |pair47| |Γ|)))
                            (labels ((|k7| (|v6|)
                              (let ((|p49| (svref (cdr |v4|) 0)))
                                (let ((|c50| 1))
                                  (let ((|c51| 2))
                                    (let ((|con52| (cons '|Nil| (vector))))
                                      (let ((|con53| (cons '|Cons| (vector |c51| |con52|))))
                                        (let ((|con54| (cons '|Cons| (vector |c50| |con53|))))
                                          (let ((|c55| 1))
                                            (let ((|c56| 2))
                                              (let ((|c57| 3))
                                                (let ((|con58| (cons '|Nil| (vector))))
                                                  (let ((|con59| (cons '|Cons| (vector |c57| |con58|))))
                                                    (let ((|con60| (cons '|Cons| (vector |c56| |con59|))))
                                                      (let ((|con61| (cons '|Cons| (vector |c55| |con60|))))
                                                        (let ((|pair62| (cons |con54| |con61|)))
                                                          (let ((|_code1028| (svref (cdr |p49|) 0)))
                                                            (let ((|Γc1029| (svref (cdr |p49|) 1)))
                                                              (let ((|ρc1030| (cons |pair62| |Γc1029|)))
                                                                (labels ((|k9| (|v8|)
                                                                  (let ((|p64| (svref (cdr |v4|) 0)))
                                                                    (let ((|c65| 1))
                                                                      (let ((|c66| 2))
                                                                        (let ((|c67| 3))
                                                                          (let ((|con68| (cons '|Nil| (vector))))
                                                                            (let ((|con69| (cons '|Cons| (vector |c67| |con68|))))
                                                                              (let ((|con70| (cons '|Cons| (vector |c66| |con69|))))
                                                                                (let ((|con71| (cons '|Cons| (vector |c65| |con70|))))
                                                                                  (let ((|c72| 1))
                                                                                    (let ((|c73| 2))
                                                                                      (let ((|c74| 3))
                                                                                        (let ((|con75| (cons '|Nil| (vector))))
                                                                                          (let ((|con76| (cons '|Cons| (vector |c74| |con75|))))
                                                                                            (let ((|con77| (cons '|Cons| (vector |c73| |con76|))))
                                                                                              (let ((|con78| (cons '|Cons| (vector |c72| |con77|))))
                                                                                                (let ((|pair79| (cons |con71| |con78|)))
                                                                                                  (let ((|_code1025| (svref (cdr |p64|) 0)))
                                                                                                    (let ((|Γc1026| (svref (cdr |p64|) 1)))
                                                                                                      (let ((|ρc1027| (cons |pair79| |Γc1026|)))
                                                                                                        (labels ((|k11| (|v10|)
                                                                                                          (let ((|p81| (svref (cdr |v6|) 0)))
                                                                                                            (let ((|c82| 1))
                                                                                                              (let ((|con83| (cons '|Some| (vector |c82|))))
                                                                                                                (let ((|c84| 2))
                                                                                                                  (let ((|con85| (cons '|Some| (vector |c84|))))
                                                                                                                    (let ((|pair86| (cons |con83| |con85|)))
                                                                                                                      (let ((|_code1022| (svref (cdr |p81|) 0)))
                                                                                                                        (let ((|Γc1023| (svref (cdr |p81|) 1)))
                                                                                                                          (let ((|ρc1024| (cons |pair86| |Γc1023|)))
                                                                                                                            (labels ((|k13| (|v12|)
                                                                                                                              (let ((|p88| (svref (cdr |v6|) 0)))
                                                                                                                                (let ((|c89| 1))
                                                                                                                                  (let ((|con90| (cons '|Some| (vector |c89|))))
                                                                                                                                    (let ((|c91| 1))
                                                                                                                                      (let ((|con92| (cons '|Some| (vector |c91|))))
                                                                                                                                        (let ((|pair93| (cons |con90| |con92|)))
                                                                                                                                          (let ((|_code1019| (svref (cdr |p88|) 0)))
                                                                                                                                            (let ((|Γc1020| (svref (cdr |p88|) 1)))
                                                                                                                                              (let ((|ρc1021| (cons |pair93| |Γc1020|)))
                                                                                                                                                (labels ((|k15| (|v14|)
                                                                                                                                                  (let ((|p95| (svref (cdr |v6|) 0)))
                                                                                                                                                    (let ((|c96| 1))
                                                                                                                                                      (let ((|con97| (cons '|Some| (vector |c96|))))
                                                                                                                                                        (let ((|con98| (cons '|None| (vector))))
                                                                                                                                                          (let ((|pair99| (cons |con97| |con98|)))
                                                                                                                                                            (let ((|_code1016| (svref (cdr |p95|) 0)))
                                                                                                                                                              (let ((|Γc1017| (svref (cdr |p95|) 1)))
                                                                                                                                                                (let ((|ρc1018| (cons |pair99| |Γc1017|)))
                                                                                                                                                                  (labels ((|k17| (|v16|)
                                                                                                                                                                    (let ((|c101| 2))
                                                                                                                                                                      (let ((|con102| (cons '|Some| (vector |c101|))))
                                                                                                                                                                        (let ((|con103| (cons '|None| (vector))))
                                                                                                                                                                          (let ((|p104| (cons |con102| |con103|)))
                                                                                                                                                                            (let ((|p105| (cons |v16| |p104|)))
                                                                                                                                                                              (let ((|p106| (cons |v14| |p105|)))
                                                                                                                                                                                (let ((|p107| (cons |v12| |p106|)))
                                                                                                                                                                                  (let ((|p108| (cons |v10| |p107|)))
                                                                                                                                                                                    (let ((|p109| (cons |v8| |p108|)))
                                                                                                                                                                                      (funcall (the function |k|) |p109|))))))))))))
                                                                                                                                                                    (funcall (the function |_code1016|) |ρc1018| #'|k17|))))))))))))
                                                                                                                                                  (funcall (the function |_code1019|) |ρc1021| #'|k15|)))))))))))))
                                                                                                                              (funcall (the function |_code1022|) |ρc1024| #'|k13|)))))))))))))
                                                                                                          (funcall (the function |_code1025|) |ρc1027| #'|k11|)))))))))))))))))))))))
                                                                  (funcall (the function |_code1028|) |ρc1030| #'|k9|)))))))))))))))))))))
                              (funcall #'|fn1007| |ρc1033| #'|k7|)))))))
                      (funcall #'|fn1012| |ρc1036| #'|k5|))))))))))))

; driver
(defun |__start| ()
  (format t "~A"
    (funcall #'|main| nil #'identity)))

