name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04-arm, macos-latest, linux-x64]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1

      - uses: actions/upload-artifact@v4
        with:
          path: .lake/build
          name: tigris-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          compression-level: 9
